### ISSUE TITLE
Issue with Sharing PVCs in ACS Community 

### ISSUE THREAD

**Issue by abdo-repos** [Alfresco/acs-deployment#1031]
I'm currently deploying Alfresco Community on a Kubernetes cluster using the Helm chart provided in the official documentation. According to the documentation, both ActiveMQ and the repository are configured to share the same Persistent Volume Claim (PVC) with the access mode set to ReadWriteOnce.

However, I'm facing an issue during the restart of the ActiveMQ pod. When ActiveMQ attempts to mount the volume, it raises the error "Device or resource busy", preventing it from starting successfully. This leads to the question of whether it is a strict requirement for both pods (ActiveMQ and the repository) to share the same PVC.

Given the constraint that my storage class doesn't support the ReadWriteMany access mode, is there a recommended approach to handle this scenario, such as creating separate PVCs for ActiveMQ and the repository and how to do it ?

**Comment by alxgomz** [comment]
Hi @abdo-repos 
I gues you're using a relatively old version of the chart. This "shared pvc" approach has been removed from our chart since 6.0.0.
[We test the community deployments](https://github.com/Alfresco/acs-deployment/blob/be3109fc945c9817c08073407f80b31de080c08e/test/community-integration-test-values.yaml#L14) with a storage definition access modes set to ReadWriteOnce so your setup should not be a pbm.

I would recommand you upgrade to the 6.0 charts

**Comment by abdo-repos** [comment]
Hi @alxgomz 

Thank you for your response. 

Currently, when I run` kubectl describe` for my deployment, it shows that the chart versions for the components are `chart=alfresco-content-services-5.3.0`, and for the ActiveMQ pod it's `chart=activemq-2.1.0`.

 I appreciate the recommendation to upgrade to version `6.0.2`. However, I have a concern about potential data loss during the upgrade process, particularly with respect to the Persistent Volume Claims (PVCs) which hold critical data .

Could you provide guidance on how to upgrade to the `6.0.2` charts without risking data loss in the PVCs? Specifically, I would like to ensure that the data in the PVCs remains intact and accessible after the upgrade.

Looking forward to your assistance on this matter.

**Comment by alxgomz** [comment]
I would recommand you read through the upgrade doc to review the changes and plan accordingly: 
* https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/upgrades.md

In particular for the persistence check out:
* https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/storage.md
* https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/upgrades.md#540-m1

**Comment by alxgomz** [comment]
Please note that this charts do not put a specific focus on upgrades. We try to be cautious and make clear what changes are making it into versions as we release ut you should defnitely tests any upgrade scenario in non-production and non-critical environments (that match you prod env) and only apply the upgrade once you're confident your scenario/prodecure works for your cluster

**Comment by abdo-repos** [comment]
@alxgomz  Thank you for your response

I have deployed the chart `6.0.2 `.

I have other questions regarding Alfresco Community deployment in Kubernetes for high availability.

  - What would be the most effective scaling strategy for achieving high availability (HA) with Alfresco Community deployed in a Kubernetes (K8s) cluster for a production environment? Should we focus on vertical scaling or horizontal scaling ?
  -  which specific components of Alfresco should we prioritize for scaling in order to optimize performance and reliability? 
  - is it safe to deploy multiple instances of the same component for better performance and redundancy in the HA setup?

Looking forward to your assistance on this matter.

**Comment by alxgomz** [comment]
Hi @abdo-repos ,

Alfresco repository is definitely the main component one needs to scale in order to cope with peak load. But in order to deal with cluster the repo needs to have shared distributed caches across all repository nodes. This eature is implemented using hazelcast in the Alfresco enterprise version and is not available in Alfresco COmmunity. So you cannot just set a replicaCount to something different from `1`. It just won't work.

**Comment by alxgomz** [comment]
If you want to know more about that I would encorage you to visit the [Alfresco Hub](https://hub.alfresco.com) or join the [discord chan](https://discordapp.com/channels/451644531323174912/451644531323174914)
