### ISSUE TITLE
Doesn't show the User List in Alfresco Community Edition 23.2.1

### ISSUE THREAD

**Issue by Sarcasticsalad** [Alfresco/acs-deployment#1182]
![Picture1](https://github.com/user-attachments/assets/e5d32c39-c537-4bef-b3e5-3154b62f4271)

Hello there, The community edition version 23.2.1 has the following issue. I used containers to install this on my system and had read a few solutions from the link here https://github.com/Alfresco/acs-community-packaging/issues/367 but i can't access the containers from my system. I am on windows 10. Any help would be appreciated !

**Comment by gionn** [comment]
It's usually a sign of a misconfiguration CSRF, without more details it's really hard to tell.
