### ISSUE TITLE
Modual Management Tool

### ISSUE THREAD

**Issue by 11quinmi** [Alfresco/acs-deployment#1190]
Im having issue with installing  Alfresco Audit Share

https://github.com/atolcd/alfresco-audit-share

Its looking for the MMT (Module Management Tool) to install the audit share but the acs-deployment doesn't seem to contain this feature,

Would someone please help me better understand this as im a complete noob!

**Comment by gionn** [comment]
Hello, don't know much about that specific module, but in general you need to build a new docker image if you want add extensions.
