### ISSUE TITLE
alfresco-common/templates/_helpers-jdbc.tpl error calling urlParse: unable to parse url

### ISSUE THREAD

**Issue by mcorvo** [Alfresco/acs-deployment#1207]
Dear all,

I'm trying to install a 23.3 instance on a K8s cluster, but the helm chart is failing because "at some point" in alfresco-common/templates/_helpers-jdbc.tpl, one function is appending a newline character which urlParse doesn't like. Here's the relevant error:

```
Error: INSTALLATION FAILED: template: alfresco-content-services/charts/alfresco-common/templates/_helpers-jdbc.tpl:124:22: executing "alfresco-common.db.driver" at <include "alfresco-common.jdbc.parser" .url>: error calling include: template: alfresco-content-services/charts/alfresco-common/templates/_helpers-jdbc.tpl:41:19: executing "alfresco-common.jdbc.parser" at <urlParse $jdbc_url>: error calling urlParse: unable to parse url: parse "postgresql://postgres-ha-primary.postgres-operator.svc:5432/alfresco **\n**  ": net/url: invalid control character in URL
helm.go:84: [debug] template: alfresco-content-services/charts/alfresco-common/templates/_helpers-jdbc.tpl:124:22: executing "alfresco-common.db.driver" at <include "alfresco-common.jdbc.parser" .url>: error calling include: template: alfresco-content-services/charts/alfresco-common/templates/_helpers-jdbc.tpl:41:19: executing "alfresco-common.jdbc.parser" at <urlParse $jdbc_url>: error calling urlParse: unable to parse url: parse "postgresql://postgres-ha-primary.postgres-operator.svc:5432/alfresco **\n**  ": net/url: invalid control character in URL
```

I'm not sure where this character comes from, but it's preventing the installation from completing. I could of course use the "internal" Alfresco DB, but given that I've got already a Postgresql cluster in my K8s instance, I'd prefer to rely on that one.

THanks in advance for any info or suggestions you could give me to bypass this issue.

Regards,

Marco

**Comment by gionn** [comment]
Ciao Marco,

would be of great help if you can provide values and specify the helm chart version to easily reproduce the issue.

**Comment by mcorvo** [comment]
Ciao Giovanni,

I'm currently using:

name: alfresco-content-services
version: 8.4.0
appVersion: 23.3.0

Please find in attach my values.yaml.
[values.txt](https://github.com/user-attachments/files/17228757/values.txt)

These are the relevant lines:

database:
  # -- Enable using an external database for Alfresco Content Services. Must disable `postgresql.enabled` when true.
  external: true
  # -- Postgresql jdbc driver name ex: org.postgresql.Driver. It should be available in the container image.
  driver: org.postgresql.Driver
  # -- External Postgresql database user
  user: alfresco
  # -- External Postgresql database password
  password: QA6fMXtdr%3EK%2F8aDFft,MJ%40p%3E
  # -- External Postgresql jdbc url ex: `jdbc:postgresql://oldfashioned-mule-postgresql-acs:5432/alfresco`
   url: 'jdbc:postgresql://alfresco:QA6fMXtdr%3EK%2F8aDFft,MJ%40p%3E@postgres-ha-primary.postgres-operator.svc:5432/alfresco'
  # -- Name of the secret managed by this chart
  configMapName: *infrastructure_cmName
  # -- Name of the secret managed by this chart
  secretName: &acs_database_secretName alfresco-cs-database
  # -- An existing secret that contains DATABASE_USERNAME and DATABASE_PASSWORD keys.
  # When using embedded postgres you need to also set `postgresql.existingSecret`.
  existingSecretName: null

Thanks in advance for your support.

Regards,

Marco

**Comment by mcorvo** [comment]
Ciao Giovanni,

correct. I forgot to mention a small fix I had to apply to templates/_helpers-database.tpl. Here's the git diff:

diff --git a/templates/_helpers-database.tpl b/templates/_helpers-database.tpl
index acfb76d..8e1a6c0 100644
--- a/templates/_helpers-database.tpl
+++ b/templates/_helpers-database.tpl
@@ -8,7 +8,9 @@ Usage: include "alfresco-content-services.database.repo" $
 {{- with .Values }}
   {{- if and (not .database.url) (not .postgresql.enabled) }}
     {{- fail "You must either set database.url or postgresql.enabled" }}
-  {{- else }}
+  {{- else if .database.url }}
+    {{- .database.url }}
+  {{ else }}
     {{- $pg_port := .postgresql.primary.service.ports.postgresql | toString }}
     {{- $pg_url := printf "postgresql://%s-%s:%s/%s" $.Release.Name .postgresql.nameOverride $pg_port .postgresql.auth.database }}
     {{- .database.url | default $pg_url }}

Consider that I'm pretty new to helm charts and my fixes are "naive" and intended to just make my application work.

Regards,

Marco

**Comment by gionn** [comment]
ok it's very similar to the PR I've just created so you were on the right path.

however the lack of trimming char at `{{ else }}` (instead of `{{- else }}`) was causing you the first error:

```
net/url: invalid control character in URL
```

The PR is now merged, so you could already test it using the master version of the chart. We still plan to release a v8.5.1 in the next coming days.

Closing for now.
