### ISSUE TITLE
Unable to use master branch because it relies on alfresco-shared-file-store container that is not published to us on Quay

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#123]
Please add something in the readme that calls out which version of acs-deployment to use for folks outside Alfresco. Thanks in advance.

**Comment by binduwavell** [comment]
Nope, this is for enterprise. And I see the container out there. So not sure what is going on. One of our SEs has been having issues using `docker-compose up` with the master branch today. It appeared to be related to this container not being availble to us on quay.io. The creds we've been given by support don't allow us to login to the quay.io UI. So our ability to find details out about containers is limited to CLI magic, which frankly is crap unless we actively download images :(

**Comment by binduwavell** [comment]
I see this image is on hub.docker.com. SE had logged into quay but not hub.docker.com. Closing this now. Although it would still be great if the README here was updated with some guidance on which tag to use for using specific versions of Alfresco.

**Comment by montgolfiere** [comment]
FYI: release tag / version matrix here:

https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-chart-releases.md

cc: @derekhulley
