### ISSUE TITLE
docker-compose invalid interpolation

### ISSUE THREAD

**Issue by ing-sdgonzales** [Alfresco/acs-deployment#1246]
# Invalid Interpolation format for "labels" 

Hello everyone, I'm trying to install the Alfresco Community Version following the steps in the official dcumentation [here](https://docs.alfresco.com/content-services/community/install/containers/docker-compose/).  

When I run the command `docker-compose -f community-compose.yaml up`
get the error:  

Invalid interpolation format for "labels" option in service "alfresco": "traefik.http.routers.solrapideny.rule=PathRegexp(\`^/alfresco/(wc)?s(ervice)?/api/solr/.*$\`)"

![image](https://github.com/user-attachments/assets/27dd88bf-74c1-4606-ab6f-f81414954dee)

### Environment:
- Ubuntu 22.04
- Docker v27.3.1
- Docker Compose v1.29.2

**Comment by ing-sdgonzales** [comment]
#  Solution

### Step 1:
- Make sure Docker Demon is active.

### Step 2:
-Add your user to docker group 
- `sudo usermod -aG <your_user>`
- `newgrp docker` 

### Step 3:
- Verify your Docker info
- `docker info`

If Docker log the info, you´re already set.

**Comment by gionn** [comment]
make sure you are using `docker compose` instead of `docker-compose` which is now deprecated and not supporting properly the labels are using now (documentation needs to be updated)
