### ISSUE TITLE
docker compose community deployment, CSRF error on Share access

### ISSUE THREAD

**Issue by nodje** [Alfresco/acs-deployment#1253]
`docker compose up comminuty-compose.yaml` on the repo version without modification works fine.

But share login on http://127.0.0.1:8080/share/page/ produces the following error:

```
share-1               | 2024-11-22T09:29:25,365 [] INFO  [webscripts.servlet.CSRFFilter] [http-nio-8080-exec-2] Possible CSRF attack noted when asserting referer header 'http://127.0.0.1:8080/share/page/'. Request: POST /share/page/dologin
share-1               | 2024-11-22T09:29:25,532 [] ERROR [alfresco.web.site] [http-nio-8080-exec-2] jakarta.servlet.ServletException: Possible CSRF attack noted when asserting referer header 'http://127.0.0.1:8080/share/page/'. Request: POST /share/page/dologin, FAILED TEST: Assert referer POST /share/page/dologin :: referer: 'http://127.0.0.1:8080/share/page/' vs server & context: http://127.0.0.1/ (string) or http://localhost:8080/share/.* (regexp)
```
I tried to deactivate CSRF validation by deactivating the Share service environment variables :
CSRF_FILTER_ORIGIN: http://localhost:8080
CSRF_FILTER_REFERER: http://localhost:8080/share/.*
but to no avail.

I've been trying to change CSRF_FILTER_* values to 127.0.0.1 based URLs and access Alfresco using this IP instead of localhost but the ERROR persists.

**Comment by alxgomz** [comment]
Can you please reset the compose file to what it's vanilla state (so at least `CSRF_FILTER_*` env vars set to use localhost as a hostname) and change the line bellow also to localhost?

https://github.com/Alfresco/acs-deployment/blob/b1a54d86a624ed905bfa60c54baa3a7dc3e3f816/docker-compose/community-compose.yaml#L36

And then restart compose?

**Comment by alxgomz** [comment]
Thanks for confirming. We'll fix that so it's consistent between repo and share.
Tracked in OPSEXP-2968
