### ISSUE TITLE
Digital Workspace Does Not Start

### ISSUE THREAD

**Issue by joefuzz** [Alfresco/acs-deployment#173]
The Alfresco Digital Workspace app hangs at the loading spinner after deploying to Minikube. 

It appears that despite the chart value telling the ingress that the path for the app is "/digital-workspace", the index.html file sets the base href value to "./". This relative path does not appear to be recognized in Chrome. When I manually set the value to "/digital-workspace/", the application works as expected.

**Comment by killerboot** [comment]
Hi, thanks for raising this.
I'll cc to @john-knowles and @DenysVuika.

**Comment by DenysVuika** [comment]
The 1.0 version should work fine, in the 1.1 beta we indeed have an issue with the './' hardcoded caused by security fixes.

**Comment by joefuzz** [comment]
For some additional context, when I ran into this issue, I was using the latest version of the chart from the alfresco-stable repo.

**Comment by DenysVuika** [comment]
@joefuzz can you please give more context? The chart references 1.0 image that has "/" basePath (actually changed to "./" if you are using docker-compose file). The chart also supports "BASEPATH" variable to customize things.

**Comment by john-knowles** [comment]
Yes, a set of clear steps to reproduce are required in order to help us reproduce the issue you are having.

**Comment by DenysVuika** [comment]
There are few improvements for the upcoming 1.1 that should solve the problem if it still exists.

**Comment by joefuzz** [comment]
I followed the instructions on the README to create the ingress and then installed the helm chart from alfresco-stable with this command:

```helm install alfresco-stable/alfresco-content-services --set externalProtocol="http" --set externalHost="<my_host>" --set externalPort="<my_port>" --set registryPullSecrets=quay-registry-secret```

Where `quay-registry-secret` refers to a mounted secret containting our partner credentials for quay.io. 

After waiting until all the pods are ready, I try to navigate to the digital workspace app at `https://<my_host>/digital-worksapce` but it hangs at the loading spinner image. When I check the console in Chrome, I see several 404 errors. Inspecting the source code shows that the base tag is this:

`<base href="./">`

**Comment by DenysVuika** [comment]
Should be working in the latest release.
