### ISSUE TITLE
volume claim alfresco-volume-claim assigned to multiple pods

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/acs-deployment#203]
Almost all pods (except solr but including e.g. activemq) are using the same volume claim. This is not possible in the infrastructure of the Alfresco customer I am working with which is based on vmware vsphere. At the moment only the postgresql volume claim can be changed by setting the property postgresql.persistence.existingClaim. All other pods are sharing the same configuration property persistence.existingClaim which makes it impossible to configure different claims without modifying the chart templates.

We would like to have an option to configure different claims for all pods that does not require forking and modifying the helm charts.

**Comment by killerboot** [comment]
Hi @torstenwerner , thanks for this enhancement request, we will track it here:
https://issues.alfresco.com/jira/browse/REPO-4472

**Comment by alxgomz** [comment]
closing as we are not using the alfresco-volume-claim anymore
