### ISSUE TITLE
no tls configuration in ingress manifests

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/acs-deployment#206]
There is no TLS support in the current ingress manifests.

**Comment by killerboot** [comment]
The TLS is configured during ingress deployment as a separate chart, please see the docs here:
https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-deployment-aws_kops.md#deploying-the-ingress-for-alfresco-content-services
The TLS config may differ for different Cloud providers, we have an example for AWS.

**Comment by bartjkdp** [comment]
Created a PR for this: https://github.com/Alfresco/acs-deployment/pull/541
