### ISSUE TITLE
broken configuration of transform-router

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/acs-deployment#207]
The imagePullSecrets do not fall back to the secrets referenced in the serviceaccount by default. Here is the patch:

    Index: helm/alfresco-content-services/templates/deployment-transform-router.yaml
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>UTF-8
    ===================================================================
    --- helm/alfresco-content-services/templates/deployment-transform-router.yaml	(date 1560973799000)
    +++ helm/alfresco-content-services/templates/deployment-transform-router.yaml	(date 1560974160000)
    @@ -17,9 +17,11 @@
             release: {{ .Release.Name }}
             component: transformrouter
         spec:
    +      {{- if .Values.registryPullSecrets }}
           # only set this secret if a private docker registry variable is defined
           imagePullSecrets:
             - name: {{ .Values.registryPullSecrets }}
    +      {{- end }}
           affinity:
             podAntiAffinity:
               preferredDuringSchedulingIgnoredDuringExecution:
    @@ -76,4 +78,4 @@
           - name: config-volume
             configMap:
               name: {{ template "alfresco.shortname" . }}-transform-routes-configmap
    -      {{- end }}
    \ No newline at end of file
    +      {{- end }}

**Comment by killerboot** [comment]
Thanks for raising this @torstenwerner

@montgolfiere Please take a look at this issue.

**Comment by danielfz** [comment]
I getting an error just doing "docker-compose up". Not sure if it's related to this.

`Pulling transform-router (quay.io/alfresco/alfresco-transform-router:1.1.0)...
ERROR: unauthorized: access to the requested resource is not authorized`

**Comment by ict-singapore** [comment]
> I getting an error just doing "docker-compose up". Not sure if it's related to this.
> 
> `Pulling transform-router (quay.io/alfresco/alfresco-transform-router:1.1.0)... ERROR: unauthorized: access to the requested resource is not authorized`

Have you received the **quay.io** credentials from Alfersco support. Only then you can download this image to build the transform-router container. More details are [here](https://docs.alfresco.com/6.1/tasks/deploy-docker-compose.html)

**Comment by montgolfiere** [comment]
Closing as per comment above.

See also https://github.com/Alfresco/acs-deployment/blob/master/README.md#other-information
