### ISSUE TITLE
yaml indentation bug

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/acs-deployment#208]
patch:

    Index: helm/alfresco-content-services/templates/deployment-transform-router.yaml
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>UTF-8
    ===================================================================
    --- helm/alfresco-content-services/templates/deployment-transform-router.yaml	(revision c6781aa1e0e6bf5b5c871e028cab1f4a490ebb5d)
    +++ helm/alfresco-content-services/templates/deployment-transform-router.yaml	(revision 309128ffecc808f94b86d7f1cfc8d0e36c2b7d5e)
    @@ -57,17 +57,17 @@
                 httpGet:
                   path: /actuator/health
                   port: {{ .Values.transformrouter.image.internalPort }}
    -              initialDelaySeconds: {{ .Values.transformrouter.livenessProbe.initialDelaySeconds }}
    -              periodSeconds: {{ .Values.transformrouter.livenessProbe.periodSeconds }}
    -              failureThreshold: 1
    -              timeoutSeconds: {{ .Values.transformrouter.livenessProbe.timeoutSeconds }}
    +            initialDelaySeconds: {{ .Values.transformrouter.livenessProbe.initialDelaySeconds }}
    +            periodSeconds: {{ .Values.transformrouter.livenessProbe.periodSeconds }}
    +            failureThreshold: 1
    +            timeoutSeconds: {{ .Values.transformrouter.livenessProbe.timeoutSeconds }}
               readinessProbe:
                 httpGet:
                   path: /actuator/health
                   port: {{ .Values.transformrouter.image.internalPort }}
    -              initialDelaySeconds: {{ .Values.transformrouter.readinessProbe.initialDelaySeconds }}
    -              periodSeconds: {{ .Values.transformrouter.readinessProbe.periodSeconds }}
    -              timeoutSeconds: {{ .Values.transformrouter.readinessProbe.timeoutSeconds }}
    +            initialDelaySeconds: {{ .Values.transformrouter.readinessProbe.initialDelaySeconds }}
    +            periodSeconds: {{ .Values.transformrouter.readinessProbe.periodSeconds }}
    +            timeoutSeconds: {{ .Values.transformrouter.readinessProbe.timeoutSeconds }}
               {{- if .Values.ai.enabled }}
               volumeMounts:
               - name: config-volume

**Comment by killerboot** [comment]
Thanks for raising this @torstenwerner 

@montgolfiere Please take a look at this issue.
