### ISSUE TITLE
no explanation on integrating another jdbc driver

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/acs-deployment#211]
The repository image ships the postgresql jdbc driver. How do i integrate a different driver such as ojdbc? I could not find an answer in the docs.

**Comment by killerboot** [comment]
Hi, if you need to extend the "standard" Docker image in any way (including the jdbc driver) you will have to build your own image.
This is explained here: https://github.com/Alfresco/acs-deployment/blob/master/docs/customising-deployment.md#k8s-deployment-customization-guidelines
