### ISSUE TITLE
Re-Label Branches or Tags to Match ACS Version Numbers

### ISSUE THREAD

**Issue by ParadoxGuitarist** [Alfresco/acs-deployment#281]
So, I'm an employee of a customer for Alfresco. We're currently undergoing some development to look at containerizing our alfresco instances and migrating away from monolithic installs. While this repo has been helpful into getting some things up and running in OpenShift, there are a few things that would be extremely useful that are currently making progress difficult: 

- ### Have the version Branch Tags match ACS Versions: 
![image](https://user-images.githubusercontent.com/6751928/68899571-d42a2d00-06e6-11ea-80fe-b7df9e37b6b5.png)
Above you can see that non of the branch names indicate what version of ACS is being deployed, but the master branch references a 6.3 Alpha image. When moving over to tags you see: 
![image](https://user-images.githubusercontent.com/6751928/68899773-3be07800-06e7-11ea-9dd8-508b66bf1d41.png)
One tag that seems to relate to an ACS release candidate (from over two years ago) and then other version numbers that don't seem to relate at all. As a customer, it sure would be nice to be able to easily find the specific version I'm looking to spin up (6.0, 6.1, alpha, RC, stable, etc. ) with the latest versions that are supported inside those different streams. Instead version 2.1.1 somehow is what translates to the stable release. 
![image](https://user-images.githubusercontent.com/6751928/68900039-d93bac00-06e7-11ea-833e-fe46b7a9f659.png)

- ### Have the Master Branch Reference Latest Stable:
I expected that the master branch was referencing the latest stable version, but that didn't seem to be the case. It's actually what kicked off this challenge of trying to find a good version to base my other configs. While I would eventually love to have an instance of latest RC candidates, it's simply not useful to me as a customer starting out with either Alfresco (If I'm considering becoming a customer) or with containers (as troubleshooting introduces codebase/image bugs instead of just configuration errors. ) 

As always thanks for your hard work, and for consideration by allowing this kind of feedback into your development and support systems. =)

**Comment by gavincornwell** [comment]
We have changed our approach since this issue was raised. We no longer maintain long lived branches and instead support all versions on master. Master remains the latest code but tags will identify stable releases that can be used to achieve reliable results.

The table of tags vs. versions that get deployed can be found here: https://github.com/Alfresco/acs-deployment/blob/master/README.md#versioning
