### ISSUE TITLE
docker-compose on ECS and ALB 

### ISSUE THREAD

**Issue by ict-singapore** [Alfresco/acs-deployment#292]
I am trying to deploy the ACS following the docker-compose file on ECS (on EC2 using Task definitions).

While most containers are started successfully,  **alfresco** and **nginx** fails.
I have alternatively tried to start the alfresco container alone and exposed ports 8080 to see if they run. Successfully connects to the port 8080, however, shows the error `Cannot find Alfresco Repository on this server. (Does this application have access to alfresco-global.properties? Does this application have cross-context permissions?)`

While trying the same way, when we bring the nginx up, it always fails. 

Is there a way to bypass the nginx and launch alfresco and share services. The reason again will be using an ELB for fronting this application rather than using the nginx. Is there a workaround for this issue?

**Comment by alf-wchong** [comment]
Is the **networkMode** task definition set to either _host_ or _awsvpc_?

**Comment by gavincornwell** [comment]
We currently don't test using ECS/Fargate so it's not possible to give an exact answer/guidance, however, I have added a story to our backlog to add an example.
