### ISSUE TITLE
Enable HTTPS on ACS

### ISSUE THREAD

**Issue by ict-singapore** [Alfresco/acs-deployment#294]
We are running ACS on Docker in EC2 (not ECS). This setup is fronted with an ELB to allow HTTPS traffic. When the client connect to https://publicurl.com/share/pages and logs in , we see the message :

`We may have hit an error or something might have been removed or deleted, so check that the URL is correct. 
Alternatively you might not have permission to view the page (it could be on a private site) or there could have been an internal error. Try checking with your IT team.
If you're trying to get to your home page and it's no longer available you should change it by clicking your name on the toolbar.`

We have tried adding the lines to the environment variable to the docker-compose file
`alfresco.context=alfresco
alfresco.host=<external-proxy-host-name>
alfresco.port=443
alfresco.protocol=https
share.context=share
share.host=<external-proxy-host-name>
share.port=443
share.protocol=https`

However, the issue remains the same. What will be the workaround

**Comment by gavincornwell** [comment]
We have a story on our backlog to provide examples of deploying containers using HTTPS and fronted by an ELB so please monitor the examples section here: https://github.com/Alfresco/acs-deployment/tree/master/docs/docker-compose/examples
