### ISSUE TITLE
Consider adding helm 3 compatibility

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#330]
I'm wondering if/when helm 3 compatibly charts will be made available?

**Comment by mteodori** [comment]
at the moment I can install successfully if I skip validation with the option `helm install --disable-openapi-validation` see: 

https://github.com/Alfresco/terraform-alfresco-process/blob/develop/modules/acs/main.tf#L86

**Comment by gavincornwell** [comment]
Helm 3 compatibility has been added to the latest charts, the latest milestone release (5.0.0-M2) can be used from stable. 

I will close the issue once 5.0.0 is released.

**Comment by gavincornwell** [comment]
The 5.0.0 charts have now been released so closing this issue.
