### ISSUE TITLE
Consider adding Docker Desktop documentation

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#331]
MiniKube has not really been a thing on desktop for over a year since Kubernetes was added to Docker Desktop. Consider documenting how to run on Docker Desktop for both Mac and Windows.

**Comment by mteodori** [comment]
well minikube is alive and well and allows much more flexibility than docker desktop most of all you can decide which version od kubernetes to run on, I am not sure thise generic documentation is really any useful as these tools change fast, it would be better to just link to the respective documentation

**Comment by gavincornwell** [comment]
We do now have documentation for deploying to docker for desktop so closing this issue.
