### ISSUE TITLE
Consider documenting how to run via helm/kubernetes with less than 16G

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#332]
I was able to run on a 16G MacBook Pro with this values.yaml: https://gist.github.com/binduwavell/868779f53da14de5a7a41759648980a3

Four key things I did:
* Reduced replica count from 2 to 1 in all cases where it is 2 by default
* Reduce memory for all containers
* Change config for liveness and readiness as the cluster takes a while to start and the default timeouts resulted in the cluster never starting
* Disabled (via CLI command listed in there) the file sync stuff as I don't need it and I wanted the resources back.

**Comment by mteodori** [comment]
the general guidelines in a chart you scaffold with `helm create mychart` suggest not adding resources at all and leave to who is installing in order to support less capable systems probably we should do the same

**Comment by gavincornwell** [comment]
The docker for desktop page has some guidance on deploying the ACS helm charts with reduced memory requirements. 

Also note the docker compose and helm deployments now make use of the "MaxRAMPercentage" JVM option so setting the container memory requirements should be sufficient.
