### ISSUE TITLE
Consider updating helm-chart-releases.md with tested Kubernetes/KubeCtl/Helm versions

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#333]
https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-chart-releases.md

These charts appear to be quite fragile relative to the exact versions of Kubernetes, helm and kubectl. As such the specific requirements (or at least what has been tested) should be documented.

**Comment by gavincornwell** [comment]
We do now specify the versions of kubectl, helm and Kubernetes we are using for testing here: https://github.com/Alfresco/acs-deployment#helm
