### ISSUE TITLE
Please create a tag for 3.1.0 (ACS 6.2.1)

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#348]
Based on your naming convention we should see a tag 3.1.0 for ACS 6.2.1 for both helm (and I hope docker-compose.) Many thanks!

**Comment by gavincornwell** [comment]
Hi Bindu,

As you can see on the [releases table](https://github.com/Alfresco/acs-deployment/blob/4.0.3/docs/helm-chart-releases.md) we had to release 6.2.1 with a new major version of the chart so the tag you're looking for is 4.0.3.

That tag does indeed cover Helm and Docker compose.

Apologies for the confusion.

Gavin
