### ISSUE TITLE
ActiveMQ java.io.EOFException

### ISSUE THREAD

**Issue by LUOBOTOUJ** [Alfresco/acs-deployment#396]
Hello
l have deployed this service with docker and when  i upload a file that size more than 10M, the service will down  and catch some error messages .

`2020-07-31 07:00:36.638 UTC [600] LOG:  unexpected EOF on client connection with an open transaction
activemq_1               |  WARN | Transport Connection to: tcp://192.168.80.3:60208 failed: java.io.EOFException
activemq_1               |  WARN | Transport Connection to: tcp://192.168.80.3:60232 failed: java.io.EOFException
share_1                  |  2020-07-31 07:00:37,122  INFO  [webscripts.connector.RemoteClient] [http-nio-8080-exec-8] Exception calling (POST) http://alfresco:8080/alfresco/s/api/upload?Alfresco-CSRFToken=AVgj3i2ZhJgcqHCLyd7AwfPITVVlRwC%2FUz1MitD6T%2Fs%3D&alf_ticket=TICKET_93f31c127341f36da120906058f832e47f128665
share_1                  |  org.apache.http.NoHttpResponseException: alfresco:8080 failed to respond
share_1                  |      at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
share_1                  |      at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
share_1                  |      at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
share_1                  |      at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
share_1                  |      at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
share_1                  |      at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
share_1                  |      at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
share_1                  |      at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
share_1                  |      at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
share_1                  |      at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
share_1                  |      at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
share_1                  |      at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
share_1                  |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
share_1                  |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
share_1                  |      at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
share_1                  |      at org.springframework.extensions.webscripts.connector.RemoteClient.service(RemoteClient.java:1167)
share_1                  |      at org.springframework.extensions.webscripts.connector.RemoteClient.call(RemoteClient.java:804)
share_1                  |      at org.springframework.extensions.webscripts.connector.HttpConnector.call(HttpConnector.java:143)
share_1                  |      at org.springframework.extensions.webscripts.connector.AuthenticatingConnector.call(AuthenticatingConnector.java:293)
share_1                  |      at org.springframework.extensions.webscripts.servlet.mvc.EndPointProxyController.handleRequestInternal(EndPointProxyController.java:328)
share_1                  |      at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
share_1                  |      at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
share_1                  |      at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
share_1                  |      at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
share_1                  |      at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
share_1                  |      at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
share_1                  |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
share_1                  |      at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
share_1                  |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
share_1                  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
share_1                  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  |      at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
share_1                  |      at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
share_1                  |      at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
share_1                  |      at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:728)
share_1                  |      at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:470)
share_1                  |      at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:395)
share_1                  |      at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:316)
share_1                  |      at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:213)
share_1                  |      at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
share_1                  |      at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
share_1                  |      at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)`

**Comment by gavincornwell** [comment]
This could be caused by many factors i.e. not enough memory allocated to one of the containers, upload limits, transformation limits etc.

We will require some more detailed reproducible steps before being able to help further however I appreciate this was raised quite some time ago so you may have moved on since.
