### ISSUE TITLE
Helm Link in Getting Started in incorrect?

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/acs-deployment#399]
I believe the link to Helm in Getting started is incorrect. Directs to non-english website

**Comment by gavincornwell** [comment]
FYI, the documentation has had a big overhaul and will be merged to master in the next day or two so the link may have been fixed already. Just to be sure though what link/page are you referring to, can you be a bit more specific?

**Comment by gavincornwell** [comment]
No response from question and I've checked all Helm links I can find so closing this issue.
