### ISSUE TITLE
prerequisites version compatibility

### ISSUE THREAD

**Issue by vprince1** [Alfresco/acs-deployment#403]
I am trying to get the latest supported versions of Docker, Kubernetes, Helm, etc for ACS 6.2.2. Can I go with the recommendation of https://github.com/Alfresco/alfresco-dbp-deployment/blob/master/README-prerequisite.md or is there a newer supported list?

Thanks,
Vijay

**Comment by gavincornwell** [comment]
Hi Vijay, 

Whilst we're updating the charts and documentation I think this is probably the best option you have for 6.2.2 at the moment to be honest.

I will make sure we add a similar table to the documentation in the repository as well.

Thanks,
Gavin

**Comment by gavincornwell** [comment]
All versioning information is now in this section: https://github.com/Alfresco/acs-deployment#versioning
