### ISSUE TITLE
Consider publishing projects that produce containers used by this project

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/acs-deployment#430]
The docs list the following Dockerfiles as being used by this project:

Container | Dockerfile Location
-- | --
alfresco | https://github.com/Alfresco/acs-packaging/blob/master/docker-alfresco/Dockerfile
share | https://github.com/Alfresco/share/blob/master/packaging/docker/Dockerfile
solr6 | https://github.com/Alfresco/InsightEngine/blob/master/search-services/packaging/src/docker/Dockerfile
digital-workspace | https://github.com/Alfresco/alfresco-digital-workspace-app/blob/develop/Dockerfile
activemq | https://github.com/Alfresco/alfresco-docker-activemq/blob/master/Dockerfile
sync-service | https://github.com/Alfresco/dsync-services/blob/master/service-sync/packaging/docker/Dockerfile
transform-router | https://github.com/Alfresco/alfresco-transform-service/blob/master/alfresco-transform-router/src/main/docker/Dockerfile
transform-core-aio | https://github.com/Alfresco/alfresco-transform-core/blob/master/alfresco-transform-core-aio/alfresco-transform-core-aio-boot/Dockerfile
shared-file-store | https://github.com/Alfresco/alfresco-shared-file-store/blob/master/controller/Dockerfile
proxy | https://github.com/Alfresco/acs-ingress/blob/master/Dockerfile

Many of these Dockerfiles are in projects that are not public. Given that we have not seen documentation on for example the shared-files-store REST API, or details on what is built into the transform-router, it can be challenging to understand how these pieces work together. Can all of these projects be made public?

**Comment by binduwavell** [comment]
FYI, I found a bunch more doc since the last time I looked into this. Having said that, I still think these projects should be made public if possible.

**Comment by gavincornwell** [comment]
The table in https://github.com/Alfresco/acs-deployment/tree/master/docs/docker-compose#reference has been updated to only include publicly accessible Dockerfiles. Unfortunately the other projects are only available as part of the Enterprise edition so we can't open those repositories.
