### ISSUE TITLE
Alfresco-search chart specifies solr.content.dir

### ISSUE THREAD

**Issue by ariksidney** [Alfresco/acs-deployment#431]
The Helm chart for alfresco-search 2.0.0 still specifies a solr.content.dir.

According to the documentation at [https://docs.alfresco.com/search-enterprise/concepts/external-properties-solr.html](https://docs.alfresco.com/search-enterprise/concepts/external-properties-solr.html), this attribute should no longer be specified.

I will create a PR for this enhancement.

**Comment by gavincornwell** [comment]
I can not find any occurrence of "solr.content.dir" is the helm charts anymore so closing.
