### ISSUE TITLE
Documentation Question: 

### ISSUE THREAD

**Issue by mtwallach** [Alfresco/acs-deployment#44]
In Option 2: Deploying.......
Update the dependencies required:
cd helm/alfresco-content-services
helm dependency update
cd ..

what do you do after "cd .."?
I ran: helm install alfresco-content-services --set externalProtocol="http" --set externalHost="192.168.99.100" --set externalPort="30341"
is that correct?

**Comment by killerboot** [comment]
Thanks for raising the issue. Indeed there is a mistake in the documentation in this section:
https://github.com/Alfresco/acs-deployment/blob/master/docs/helm-deployment-minikube.md#option-2-deploying-alfresco-content-services-from-the-source-code

Your command seems to be correct.  The section should have these lines:
```
helm install alfresco-content-services --set externalProtocol="http" --set externalHost="172.31.147.123" --set externalPort="30917"
```

**Comment by killerboot** [comment]
The documentation was updated.
