### ISSUE TITLE
Use Statefulset instead of deployment for Solr

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/acs-deployment#444]
Hi,

shouldn't solr be deployed using a statefulset instead of a deployment in a multi master configuration because the replicas cannot share the same volume?

All replicas but one fails with the current helm chart when I set the replica count to a value > 1.

Regards,
Torsten

**Comment by andreaskring** [comment]
The same goes for repository Deployment - this should also be change to a StatefulSet

**Comment by gavincornwell** [comment]
Tracked internally via https://alfresco.atlassian.net/browse/OPSEXP-800

**Comment by ariksidney** [comment]
As far as I can see it, the repository don't have to be a statefulSet (at least when your contentstore is on a RWX volume), but activeMQ should probably be a statefulSet aswell.

**Comment by alxgomz** [comment]
Following the recent updates on both Ansible playbook and Helm charts I'm closing this issue as we don't recommend using Solr workload in-cluster so we prefer avoiding to provide features such as HA for Solr within Helm as it would create confusion on the relevance of runnign Solr for production workload in kubernetes.
See https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/examples/search-services.md
