### ISSUE TITLE
can we get a process in place for tagging public DBP repos?

### ISSUE THREAD

**Issue by ryandawsonuk** [Alfresco/acs-deployment#445]
Currently github.com/Activiti/activiti-cloud-sso-idm points here and so Activiti is releasing monthly through https://hub.docker.com/r/activiti/activiti-cloud-sso-idm/tags/

Activiti can stop doing this but there should be alternative tags available to point to so that Activiti can say which version of a DBP component each Activiti release works against (much like in https://github.com/Activiti/activiti-cloud-examples/blob/7-201712-EA/docker/infrastructure-docker.yml#L9)

This presently applies to keycloak-deployment and gateway

**Comment by Marina-Alfresco** [comment]
Moving the ticket to an active repository for visibility

**Comment by gavincornwell** [comment]
No longer applicable so closing.
