### ISSUE TITLE
Docker Compose fails on Centos 8

### ISSUE THREAD

**Issue by adamparker** [Alfresco/acs-deployment#454]
On Centos 8 there are some errors relating to the firewall and iptables.

The share container fails to start because it is unable to access Postgres.

SOLR6 goes round in circles with a NoRouteToHost Exceptions which then fill up the logs.

I added a rule to allow 8080 on the interface but I only get a 502 bad gateway response.  This post has the same issue: https://hub.alfresco.com/t5/alfresco-content-services-forum/centos-8-502-bad-gateway/m-p/297845/highlight/false#M18673

I tried to disable firewalld entirely, but this prevented the containers from starting.  However, if I run 'docker-compose start' and then immediately disable firewalld, everything starts up and works.

I am using 'sudo docker-compose start'.

**Comment by gavincornwell** [comment]
Tracked internally with https://alfresco.atlassian.net/browse/OPSEXP-808

**Comment by gavincornwell** [comment]
The [fundamental issue here](https://www.reddit.com/r/docker/comments/d8j8jj/bad_news_for_those_wanting_to_use_docker_in) is that CentOS/RHEL have removed docker from their distribution by default: , they [now recommend](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index) you use their own tools i.e. "podman" for running single containers and OpenShift for multiple containers.

However after some research we found it is possible to get it working if you follow these steps:

1. Install iptables (yum install -y iptables)
2. [Install Docker](https://computingforgeeks.com/install-docker-and-docker-compose-on-rhel-8-centos-8/)
3. [Install Docker Compose](https://computingforgeeks.com/how-to-install-latest-docker-compose-on-linux/)
4. Run "docker-compose up"
