### ISSUE TITLE
How to add ssl certificate for alfresco content service,need to use with https access.

### ISSUE THREAD

**Issue by kphareesh1994** [Alfresco/acs-deployment#455]
I have downloaded the acs-community edition docker-compose file in the centOS server i have did docker-compose up,all the images and containers are created and i have configured with LDAP application is up and running. When i am adding SSL certificate in the nginx container for https access for the URL.  i have copied the SSL certificate and key file into the container and in the nginx.conf folder i have added the certificate path and reloaded the nginx services,even though the URL is not opening with https. can anyone help in resolving this issue

**Comment by gavincornwell** [comment]
We have a story on our backlog to provide examples of deploying containers using HTTPS and fronted by an ELB so please monitor the examples section here: https://github.com/Alfresco/acs-deployment/tree/master/docs/docker-compose/examples
