### ISSUE TITLE
Increase view file limit

### ISSUE THREAD

**Issue by saigop** [Alfresco/acs-deployment#456]
Am using CentOS 7 and any files either doc, docx or xlsx, xls below 1 MB am able to preview, but when its more than 1MB am not able to preview. All I get a message like 

> This document can't be previewed.
Click here to download it.

What parameter do I need to change in docker-compose.yml file...?

Anyone facing this issue?

Thanks

**Comment by gavincornwell** [comment]
Potential answer provided so closing.
