### ISSUE TITLE
Docker Desktop Kubernetes deployment with Helm charts - fails to access services through nginx ingress

### ISSUE THREAD

**Issue by Jarlsb3rg** [Alfresco/acs-deployment#460]
Hi,

I am failing to deploy Alfresco using the instructions specified here: https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md. I have tried different ingress controllers and different versions of Alfresco (both community and enterprise). The problem seems to be related to configuration of the ingress.

These are the steps I perform:

```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

helm repo update

kubectl create namespace alfresco

helm install acs-ingress ingress-nginx/ingress-nginx --set controller.scope.enabled=true --set controller.scope.namespace=alfresco --set rbac.create=true --atomic --namespace alfresco

helm repo add alfresco https://kubernetes-charts.alfresco.com/stable

helm install acs alfresco/alfresco-content-services --devel \
--values=community_values.yaml \
--set externalPort="80" \
--set externalProtocol="http" \
--set externalHost="localhost" \
--atomic \
--timeout 10m0s \
--namespace=alfresco
````

This is the error message I get:

```
Error: release acs failed, and has been uninstalled due to atomic being set: admission webhook "validate.nginx.ingress.kubernetes.io" denied the request:
-------------------------------------------------------------------------------
Error: exit status 1
2020/11/17 08:32:29 [emerg] 456#456: location "^(/.*/service/api/solr/.*)$" cannot be inside the exact location "/api-explorer" in /tmp/nginx-cfg470113740:509
nginx: [emerg] location "^(/.*/service/api/solr/.*)$" cannot be inside the exact location "/api-explorer" in /tmp/nginx-cfg470113740:509
nginx: configuration file /tmp/nginx-cfg470113740 test failed

-------------------------------------------------------------------------------
```

I tried to turn off admissionWebhooks in nginx Ingress, but then I just moved the errors to the ingress-logs instead (--set controller.admissionWebhooks.enabled=false).

I tried to troubleshoot the ingress, but I didn't manage to identify the error.

```
kubectl get ing -n alfresco
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
NAME                         CLASS    HOSTS   ADDRESS     PORTS   AGE
acs-alfresco-cs-repository   <none>   *       localhost   80      3m5s
acs-alfresco-cs-share        <none>   *       localhost   80      3m5s



kubectl describe ing acs-alfresco-cs-share -n alfresco
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             acs-alfresco-cs-share
Namespace:        alfresco
Address:          localhost
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /share   acs-alfresco-cs-share:80   10.1.1.22:8080)
Annotations:  kubernetes.io/ingress.class: nginx
              meta.helm.sh/release-name: acs
              meta.helm.sh/release-namespace: alfresco
              nginx.ingress.kubernetes.io/configuration-snippet:
                location ~ ^(/.*/proxy/alfresco/api/solr/.*)$ {return 403 ;}
                            location ~ ^(/.*/-default-/proxy/alfresco/api/.*)$ {return 403;}
              nginx.ingress.kubernetes.io/proxy-body-size: 5g
Events:
  Type    Reason  Age                    From                      Message
  ----    ------  ----                   ----                      -------
  Normal  Sync    2m49s (x2 over 3m44s)  nginx-ingress-controller  Scheduled for sync
```

Is there anyone who is able to see what I'm doing wrong?
I have updated Helm and kubectl to latest version.

**Comment by gavincornwell** [comment]
Hi @Jarlsb3rg, I don't see anything obvious you have done wrong. 

As we are not pinning the version of ingress there is a slight chance they have done an update that is incompatible. I've added a task to our backlog to investigate.

**Comment by Jarlsb3rg** [comment]
Hi @gavincornwell, thank you for taking the effort of doing that!

**Comment by gavincornwell** [comment]
@Jarlsb3rg You're welcome. One quick clarification question are using Docker for Desktop Mac or Windows?

**Comment by Jarlsb3rg** [comment]
Hi @gavincornwell. I'm using Docker Desktop for Windows.

**Comment by gavincornwell** [comment]
Hi @Jarlsb3rg As I suspected a new version of nginx ingress has been released which appears to now validate the ingress rules and prevents deployment.

Whilst we're investigating a fix for that we have updated the instructions to pin the version of the nginx ingress chart we know works: https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md#ingress

Please give this a try and let us know how it goes.

**Comment by Jarlsb3rg** [comment]
Thank you @gavincornwell. I managed to deploy the community version now on external port 443.

I still fail to get the enterprise version working as it just keeps timing out, but that is most likely related to something else. I will try to get more details from logs etc.

Thanks for the help!

**Comment by gavincornwell** [comment]
You're welcome and thanks for the update.

If you're having issues with Enterprise it's most likely to be a resource issue i.e. not enough memory to create the required pods. I would recommend trying Lens (https://k8slens.dev) as it helps with troubleshooting issues like that.
