### ISSUE TITLE
Running docker-compose startup scripts behind Apache reverse proxy

### ISSUE THREAD

**Issue by whotopia** [Alfresco/acs-deployment#466]
We'd like to get the docker-compose for community edition working within a docker-enabled Linux Container (LXC) running docker. In another container we have Apache web service which has a virtual host set up to reverse proxy to Alfresco.  

In Apache (we have the Nginx from docker-compose on port 80):

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Port "443"
    RequestHeader set X-Forwarded-Proto "https"
    ProxyPass / http://10.10.10.120/ nocanon timeout=1200
    ProxyPassReverse  / http://10.10.10.120/

in the Docker file we have tried:

                -Dalfresco.host=external.host.DNS.name                                                      
                -Dalfresco.port=443                                                                        
                -Dshare.host=external.host.DNS.name                                                         
                -Dshare.port=443                                                                           
                -Dshare.context=share                                                                      
                -Dalfresco.protocol=https                                                                  
                -Dhttps.proxyHost=external.host.DNS.name                                                    
                -Dhttp.proxyHost=external.host.DNS.name                                                     
                -DproxySet=true                                                                            
                -Daos.baseUrlOverwrite=https://external.host.DNS.namealfresco/aos        

The problem we then see is that after login we see Cross site errors, and are met with "Something's wrong with this page..." upon login.  And " .servlet.ServletException: Possible CSRF attack noted when asserting referer header " in the share_1/nginx logs.  

I realise that we can dig into the tomcat configs to make necessary changes.  However, I would like to know if this can all be dealt with somehow cleanly by just changing/adding parameters to docker-compose.yml file?

Thanks!

**Comment by gavincornwell** [comment]
If you're using different domains you'll have to either disable CSRF (not recommended) or configure it to allow requests from the other domain. This page might help: https://docs.alfresco.com/community/concepts/repository-csrf-policy.html
