### ISSUE TITLE
Disabling ActiveMQ in Helm chart does not work

### ISSUE THREAD

**Issue by andreaskring** [Alfresco/acs-deployment#476]
When deploying the Alfresco Community edition via the Helm Charts with ActiveMQ disabled, i.e. by setting/overwriting the following in `community_values.yaml` with
```
activemq:
  enabled: false
```
Alfresco hangs when it tries to start the messaging subsystem. The problem seems to be due to [these lines](https://github.com/Alfresco/acs-deployment/blob/f6dc2cb26c6d689f87293c33db54774c49b0be83/helm/alfresco-content-services/templates/config-repository.yaml#L115-L117) in the `config-repository.yaml`:
```
     {{- if .Values.activemq.enabled }}
      -Dmessaging.broker.url=failover:(nio://{{ .Release.Name }}-activemq-broker:61616)?timeout=3000&jms.useCompression=true
      -Dmessaging.broker.username={{ .Values.activemq.adminUser.username }}
      -Dmessaging.broker.password={{ .Values.activemq.adminUser.password }}
      {{- else }}
      -Dmessaging.broker.url={{ .Values.messageBroker.url | default (printf "failover:(nio://%s-activemq-broker:61616)?timeout=3000&jms.useCompression=true" .Release.Name)}}
      -Dmessaging.broker.username={{ .Values.messageBroker.user }}
      -Dmessaging.broker.password={{ .Values.messageBroker.password }}
      {{- end }}
```

If ActiveMQ is disabled shouldn't the `else` block be replaced with `-Dmessaging.subsystem.autoStart=false`, i.e. the entire thing should look like this?
```
     {{- if .Values.activemq.enabled }}
      -Dmessaging.broker.url=failover:(nio://{{ .Release.Name }}-activemq-broker:61616)?timeout=3000&jms.useCompression=true
      -Dmessaging.broker.username={{ .Values.activemq.adminUser.username }}
      -Dmessaging.broker.password={{ .Values.activemq.adminUser.password }}
      {{- else }}
      -Dmessaging.subsystem.autoStart=false
      {{- end }}
```

**Comment by andreaskring** [comment]
Follow-up comment: I was using Alfresco Community repository version 6.2.2-RC1 when testing the above.

**Comment by andreaskring** [comment]
Similar issues are also found in the ConfigMaps for ImageMagick, PDFrenderer and LibreOffice, e.g. when ActiveMQ is disabled, the logs from the LibreOffice pod shows lines like this:
```
2020-12-15 07:42:23.305 ERROR 1 --- [enerContainer-1] o.s.j.l.DefaultMessageListenerContainer  : Could not refresh JMS Connection for destination 'org.alfresco.transform.engine.libreoffice.acs' - retrying using FixedBackOff{interval=5000, currentAttempts=326, maxAttempts=unlimited}. Cause: Could not connect to broker URL: nio://my-alf-activemq-broker:61616. Reason: java.net.UnknownHostException
```
i.e. the LibreOffice pod tried to contact ActiveMQ even though this has been disabled.

**Comment by gavincornwell** [comment]
Hi @andreaskring sorry to hear you've had problems deploying the system.

ActiveMQ is actually a requirement for the repository, this is why you're seeing the hang. There is actually a bug there which we have fixed recently, the system will now log a warning but this hasn't made it to community builds yet.

FYI, the "activemq.enabled" flag is provided to disable the pod based ActiveMQ so that you can configure the system to use an external ActiveMQ system.

If you want to disable the transformation engines you might find this page useful: https://docs.alfresco.com/transform1.2/concepts/transform-local-legacy.html

**Comment by andreaskring** [comment]
Hi @gavincornwell 

Thanks for you answer and for clarifying the meaning of the `activemq.enabled` flag. I guess we can close this issue again.
