### ISSUE TITLE
Read timeout error on search scheduler worker while starting up containers

### ISSUE THREAD

**Issue by abhinavmishra14** [Alfresco/acs-deployment#490]
Read timeout error on search scheduler worker while starting up containers.

Used this latest version of docker-compose: https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml

`alfresco_1            | 2021-02-09 18:10:02,061  ERROR [quartz.core.JobRunShell] [SearchScheduler_Worker-1] Job Solr.SolrWatcher threw an unhandled Exception:
alfresco_1            | org.alfresco.error.AlfrescoRuntimeException: 01090038 Read timed out
alfresco_1            |         at org.alfresco.repo.search.impl.solr.AbstractSolrAdminHTTPClient.getOperation(AbstractSolrAdminHTTPClient.java:96)
alfresco_1            |         at org.alfresco.repo.solr.SOLRAdminClient.executeAction(SOLRAdminClient.java:221)
alfresco_1            |         at org.alfresco.repo.solr.SOLRAdminClient$SolrTracker.pingSolr(SOLRAdminClient.java:333)
alfresco_1            |         at org.alfresco.repo.solr.SOLRWatcherJob.execute(SOLRWatcherJob.java:54)
alfresco_1            |         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
alfresco_1            |         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
alfresco_1            | Caused by: java.net.SocketTimeoutException: Read timed out
alfresco_1            |         at java.base/java.net.SocketInputStream.socketRead0(Native Method)
alfresco_1            |         at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
alfresco_1            |         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
alfresco_1            |         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
alfresco_1            |         at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
alfresco_1            |         at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
alfresco_1            |         at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
alfresco_1            |         at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
alfresco_1            |         at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
alfresco_1            |         at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
alfresco_1            |         at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
alfresco_1            |         at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
alfresco_1            |         at org.alfresco.repo.search.impl.solr.AbstractSolrAdminHTTPClient.getOperation(AbstractSolrAdminHTTPClient.java:73)
alfresco_1            |         ... 5 more
alfresco_1            | 2021-02-09 18:10:02,064  ERROR [quartz.core.ErrorLogger] [SearchScheduler_Worker-1] Job (Solr.SolrWatcher threw an exception.
alfresco_1            | org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: org.alfresco.error.AlfrescoRuntimeException: 01090038 Read timed out]
alfresco_1            |         at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
alfresco_1            |         at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
alfresco_1            | Caused by: org.alfresco.error.AlfrescoRuntimeException: 01090038 Read timed out
alfresco_1            |         at org.alfresco.repo.search.impl.solr.AbstractSolrAdminHTTPClient.getOperation(AbstractSolrAdminHTTPClient.java:96)
alfresco_1            |         at org.alfresco.repo.solr.SOLRAdminClient.executeAction(SOLRAdminClient.java:221)
alfresco_1            |         at org.alfresco.repo.solr.SOLRAdminClient$SolrTracker.pingSolr(SOLRAdminClient.java:333)
alfresco_1            |         at org.alfresco.repo.solr.SOLRWatcherJob.execute(SOLRWatcherJob.java:54)
alfresco_1            |         at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
alfresco_1            |         ... 1 more
alfresco_1            | Caused by: java.net.SocketTimeoutException: Read timed out
alfresco_1            |         at java.base/java.net.SocketInputStream.socketRead0(Native Method)
alfresco_1            |         at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
alfresco_1            |         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
alfresco_1            |         at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
alfresco_1            |         at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
alfresco_1            |         at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
alfresco_1            |         at org.apache.commons.httpclient.HttpParser.readRawLine(HttpParser.java:78)
alfresco_1            |         at org.apache.commons.httpclient.HttpParser.readLine(HttpParser.java:106)
alfresco_1            |         at org.apache.commons.httpclient.HttpConnection.readLine(HttpConnection.java:1116)
alfresco_1            |         at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.readLine(MultiThreadedHttpConnectionManager.java:1413)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodBase.readStatusLine(HttpMethodBase.java:1973)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1735)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
alfresco_1            |         at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
alfresco_1            |         at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
alfresco_1            |         at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
alfresco_1            |         at org.alfresco.repo.search.impl.solr.AbstractSolrAdminHTTPClient.getOperation(AbstractSolrAdminHTTPClient.java:73)
alfresco_1            |         ... 5 more`

**Comment by gavincornwell** [comment]
Being tracked internally via https://alfresco.atlassian.net/browse/OPSEXP-805

**Comment by gavincornwell** [comment]
It seems this is dependent on the system performance i.e. I was able to reproduce the issue but a colleague couldn't. I've increased the connection timeout value (solr.http.connection.timeout) in PR: https://github.com/Alfresco/acs-deployment/pull/510

This is now fixed on master.
