### ISSUE TITLE
Google docs related BeanCreationException

### ISSUE THREAD

**Issue by abhinavmishra14** [Alfresco/acs-deployment#491]
This seems to be a long running issue since the 6.2 version. It still persist with latest versions: https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml

`t: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googleDocsImportFormats' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/google-customResponse-context.xml]: Cannot resolve reference to bean 'GoogleDocsService' while setting bean property 'googledocsService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GoogleDocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Cannot resolve reference to bean 'googledocsService' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            | 2021-02-09 18:10:01,510  WARN  [management.subsystems.ChildApplicationContextFactory] [localhost-startStop-1] Startup of 'googledocs' subsystem, ID: [googledocs, drive] failed
alfresco_1            | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googleDocsImportFormats' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/google-customResponse-context.xml]: Cannot resolve reference to bean 'GoogleDocsService' while setting bean property 'googledocsService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GoogleDocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Cannot resolve reference to bean 'googledocsService' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1691)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1436)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
alfresco_1            |         at org.alfresco.repo.management.subsystems.ChildApplicationContextFactory$ApplicationContextState.start(ChildApplicationContextFactory.java:824)
alfresco_1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.start(AbstractPropertyBackedBean.java:1098)
alfresco_1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.onApplicationEvent(AbstractPropertyBackedBean.java:637)
alfresco_1            |         at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:221)
alfresco_1            |         at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:186)
alfresco_1            |         at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:206)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:426)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:943)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
alfresco_1            |         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
alfresco_1            |         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
alfresco_1            |         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
alfresco_1            |         at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
alfresco_1            |         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
alfresco_1            |         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco_1            |         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
alfresco_1            |         at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
alfresco_1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150)
alfresco_1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140)
alfresco_1            |         at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1            |         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:717)
alfresco_1            |         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
alfresco_1            |         at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
alfresco_1            |         at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
alfresco_1            |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
alfresco_1            |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
alfresco_1            |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
alfresco_1            |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
alfresco_1            |         at java.base/java.lang.Thread.run(Thread.java:834)
alfresco_1            | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GoogleDocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Cannot resolve reference to bean 'googledocsService' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1691)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1436)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
alfresco_1            |         ... 43 more
alfresco_1            | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
alfresco_1            |         ... 53 more
alfresco_1            | Caused by: java.lang.NullPointerException
alfresco_1            |         at java.base/java.io.Reader.<init>(Reader.java:167)
alfresco_1            |         at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
alfresco_1            |         at org.alfresco.integrations.google.docs.service.GoogleDocsServiceImpl.init(GoogleDocsServiceImpl.java:344)
alfresco_1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
alfresco_1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
alfresco_1            |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1            |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeCustomInitMethod$7(AbstractAutowireCapableBeanFactory.java:1904)
alfresco_1            |         at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1903)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1856)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
alfresco_1            |         ... 60 more
alfresco_1            | 2021-02-09 18:10:01,514  ERROR [management.subsystems.AbstractPropertyBackedBean] [localhost-startStop-1] Error auto-starting subsystem
alfresco_1            | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googleDocsImportFormats' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/google-customResponse-context.xml]: Cannot resolve reference to bean 'GoogleDocsService' while setting bean property 'googledocsService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GoogleDocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Cannot resolve reference to bean 'googledocsService' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1691)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1436)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
alfresco_1            |         at org.alfresco.repo.management.subsystems.ChildApplicationContextFactory$ApplicationContextState.start(ChildApplicationContextFactory.java:824)
alfresco_1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.start(AbstractPropertyBackedBean.java:1098)
alfresco_1            |         at org.alfresco.repo.management.subsystems.AbstractPropertyBackedBean.onApplicationEvent(AbstractPropertyBackedBean.java:637)
alfresco_1            |         at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEventInternal(SafeApplicationEventMulticaster.java:221)
alfresco_1            |         at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:186)
alfresco_1            |         at org.alfresco.repo.management.SafeApplicationEventMulticaster.multicastEvent(SafeApplicationEventMulticaster.java:206)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:426)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:943)
alfresco_1            |         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
alfresco_1            |         at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
alfresco_1            |         at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
alfresco_1            |         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
alfresco_1            |         at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
alfresco_1            |         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
alfresco_1            |         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
alfresco_1            |         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
alfresco_1            |         at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
alfresco_1            |         at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:129)
alfresco_1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:150)
alfresco_1            |         at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:140)
alfresco_1            |         at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1            |         at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:717)
alfresco_1            |         at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
alfresco_1            |         at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
alfresco_1            |         at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1859)
alfresco_1            |         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
alfresco_1            |         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
alfresco_1            |         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
alfresco_1            |         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
alfresco_1            |         at java.base/java.lang.Thread.run(Thread.java:834)
alfresco_1            | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'GoogleDocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Cannot resolve reference to bean 'googledocsService' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1691)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1436)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
alfresco_1            |         ... 43 more
alfresco_1            | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'googledocsService' defined in file [/usr/local/tomcat/webapps/alfresco/WEB-INF/classes/alfresco/subsystems/googledocs/drive/googledocs-context.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
alfresco_1            |         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
alfresco_1            |         at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
alfresco_1            |         ... 53 more
alfresco_1            | Caused by: java.lang.NullPointerException
alfresco_1            |         at java.base/java.io.Reader.<init>(Reader.java:167)
alfresco_1            |         at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:72)
alfresco_1            |         at org.alfresco.integrations.google.docs.service.GoogleDocsServiceImpl.init(GoogleDocsServiceImpl.java:344)
alfresco_1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
alfresco_1            |         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
alfresco_1            |         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
alfresco_1            |         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$invokeCustomInitMethod$7(AbstractAutowireCapableBeanFactory.java:1904)
alfresco_1            |         at java.base/java.security.AccessController.doPrivileged(Native Method)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1903)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1856)
alfresco_1            |         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
alfresco_1            |         ... 60 more`

**Comment by gavincornwell** [comment]
This is being tracked internally via: https://alfresco.atlassian.net/browse/GOOGLEDOCS-501 and will be fixed in the forthcoming Community release.

**Comment by gavincornwell** [comment]
This is now fixed with the latest Community docker compose file.
