### ISSUE TITLE
Min requirements of 10-16GB for a single installatation is a large footprint

### ISSUE THREAD

**Issue by shazada** [Alfresco/acs-deployment#51]
With the setup chosen I think the extra overhead for the 4 additional components will probably add up too much for small deployments.

I'm opting for a feature to have 2 versions:
1. Current Enterprise Cluster footprint --> min 10-16GB
2. Similar as the Community deployment https://github.com/Alfresco/acs-community-deployment/blob/master/docker-compose/docker-compose.yml --> min 6-10GB by combing the 4 components in 1

Point 2 could easily be a flag Enterprise/Community to get the different wars/modules etc.

If needed I can raise a JIRA issue or in the Enterprise support portal :).

Great work!

**Comment by derekhulley** [comment]
Thank you for the feedback, @shazada.
16GB for an Enterprise deployment with resilience and failover seems unnecessarily small.
Are you able to describe the use case you are attempting to meet?

We will not combine the two deployment implementations at this stage; we need to keep the option open to make use of customer-only images, even though there are none of those in our charts, at present.

**Comment by shazada** [comment]
@derekhulley sure.
16GB for production in a cluster environment is no big issue :).
But to have acceptance for the same ammount and test is too much.
And there are many Enterprise customers at the moment who don't even have cluster in The Netherland where we operate.

Typically our local government base looks like this:
- Test --> singe server all-in 4GB-6GB RAM
- Acceptance --> 50% single server all-in 6GB-10GB
- Production --> 50% single server all-in 8GB-24GB

So these are the use-cases at the moment and it's difficult to get more RAM :).

**Comment by derekhulley** [comment]
From an engineering perspective, we would regard a single server as a test environment; we appreciate that your definition and support levels will be different.

Running K8s on a single server has no benefit; spot instances and small instances on AWS are cheap.
For both Docker Compose and K8s, you can trim the size of the JVMs and images; the configuration is quite explicit in the files here; you can copy those and adjust and test, as required.

Alternatively, use the dockerfiles we provide to create your own all-in-one image and deploy that how you want.

**Comment by shazada** [comment]
Thanks Derek, I'll file an Enterprise support :). Not everyone is on Amazon AWS like you assume.

**Comment by derekhulley** [comment]
We know they are not :-) ... yet.
