### ISSUE TITLE
Pulling Custom Images from Multiple Private Docker Registries

### ISSUE THREAD

**Issue by jeffkrull** [Alfresco/acs-deployment#513]
After creating a custom Alfresco Enterprise image with custom AMPs and other code, as well as a new JDBC driver, we are storing this new image on Docker Hub. However, we're storing this image in a private Docker Hub registry. The helm templates only support one value for imagePullSecrets, which means that you can't simultaneously pull from the official Alfresco quay.io registry AND a private Docker Hub registry. A workaround for this is to use "docker pull" to download Docker Hub container images locally, and then set pullPolicy to Never in order to prevent fetching from Docker Hub, but it would be ideal to allow for multiple imagePullSecrets values to support pulling custom ACS images in addition to unmodified ACS components from quay.io.

**Comment by gavincornwell** [comment]
Hi @jeffkrull, you're right the helm templates only support one value for imagePullSecrets, however, you can put multiple sets of credentials within that secret.

You can login to DockerHub AND quay.io in the terminal which adds both sets of credentials to .docker/config.json. Then use that file to create your secret:

`kubectl create secret generic my-registry-secret --from-file=.dockerconfigjson=/home/travis/.docker/config.json --type=kubernetes.io/dockerconfigjson -n $namespace`

and then use that with your helm install command

`helm install ...... --set global.alfrescoRegistryPullSecrets=my-registry-secret`

Hope that helps!

**Comment by jeffkrull** [comment]
I will try this! Thank you! It might be useful to update the README for custom images to include this information, as this is the first I'd heard of it. I am still new to Helm deployments, and this is extremely useful to know.

**Comment by gavincornwell** [comment]
Agreed about adding to the documentation, we only recently discovered this ourselves ;-)

**Comment by gavincornwell** [comment]
I've added some information to the following pages/section:

- https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/examples/customisation-guidelines.md#using-images-from-multiple-docker-registries
- https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md#enterprise
- https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/eks-deployment.md#docker-registry-secret
