### ISSUE TITLE
Helm Deployment Incompatible with SQL Server External Database

### ISSUE THREAD

**Issue by jeffkrull** [Alfresco/acs-deployment#530]
Using a SQL Server backend database, the connection string resembles something like this: 

`jdbc:sqlserver://localhost:1433;databaseName=alfresco;lockTimeout=1000;`

All of the JDBC parameters are passed in to Alfresco as part of CATALINA_OPTS, but semicolons are considered special characters in this scenario. As such, trying to use a SQL Server JDBC URL causes the repository pod to fail to start, as Java can't even initialize Tomcat.

**Comment by gavincornwell** [comment]
@jeffkrull Thank you for reporting this, we are tracking this internally via https://alfresco.atlassian.net/browse/OPSEXP-852

**Comment by jeffkrull** [comment]
We were able to find a solution for this problem. The URL needs to be escaped in values.yaml or in the --set parameter, for example: `jdbc:sqlserver://localhost:1433\\;databaseName=AlfDev\\;lockTimeout=1000\\;` Then the value will be escaped in CATALINA_OPTS, and Tomcat can start correctly.

**Comment by gavincornwell** [comment]
Thanks for the update and workaround, we have added that information to the documentation.
