### ISSUE TITLE
Alfresco volume claim cannot be mounted across Kubernetes cluster nodes

### ISSUE THREAD

**Issue by jeffkrull** [Alfresco/acs-deployment#543]
Using a Kubernetes cluster in Azure AKS that consists of two nodes, the Alfresco helm charts have difficulty deploying with the alfresco-volume-claim. The way the PVC is configured, it will deploy on only one node, and if the Alfresco pod(s) are scheduled on the other node, they are unable to mount the PVC, and the installation fails to start. In our deployment tests, using the standard 2 pod replica count for Alfresco repository, one of the two pods is scheduled for the node with the PVC, and the second pod is scheduled on the other node. The second node is not able to start. Occasionally trying to deploy Alfresco with only one replica fails to start, if Kubernetes schedules the PVC for one node, and the repository pod for the other node, for the same reason. From my research, I believe this is an issue not just with Azure AKS, but also with EKS.

**Comment by gavincornwell** [comment]
Hi @jeffkrull thanks for highlighting this. When deploying to AWS EKS we are are using a shared file system underneath the persistent volume i.e. EFS which avoids the issues you describe. I'm not familiar with Azure so not sure if they have an equivalent to EFS.

We have just started a project to document the deployment of our Helm charts on Azure so please keep an eye on the documentation in this repository.

**Comment by jeffkrull** [comment]
I discovered a solution for this, by creating a new StorageClass using Azure Files, and then setting the Persistence in the Helm charts to use this new storage class. I can now create multiple repository nodes without issues binding the PVC.

**Comment by gregheller** [comment]
Hi @gavincornwell , does this work if you are using the S3 connector. Should the alfresco-storage-claim still use something like NFS or EFS as the storage class ? Could you use a statefulSet here with EBS for each acs pod since really when using S3 as the contentStore you really don't need a shared file system?

**Comment by alxgomz** [comment]
Closing this issue as we are not using the alfresco-volume-claim anymore.
