### ISSUE TITLE
TLS is not working

### ISSUE THREAD

**Issue by jeffkrull** [Alfresco/acs-deployment#550]
I've installed Alfresco into my cluster, using version 5.1.0-A1 from the Incubator charts, in order to get access to the TLS settings for the repository, workspace, and share. However, no matter what I do, my ingress load balancer will not provide my SSL certificates. I've verified the ingress is set up and sees the tls secret I've provided during installation, but I keep getting the Kubernetes Ingress Controller Fake Certificate when trying to view it in a browser.

**Comment by mteodori** [comment]
check the rendered ingress templates from the chart have the expected settings or verify your ingress setup following the ingress-nginx documentation https://kubernetes.github.io/ingress-nginx/user-guide/tls/
