### ISSUE TITLE
External DNS for Alfresco deployment

### ISSUE THREAD

**Issue by naveen-armedia** [Alfresco/acs-deployment#562]
Hi there,

I would like know is it required to have an DNS for Alfresco deployment in EKS...?

**Comment by mteodori** [comment]
no, but for EKS or any other helm k8s install you would probably want to set a hostname on your ingress rules and have that value on your DNS configured to reach the ingress controller load balancer either manually or automatically installing https://github.com/kubernetes-sigs/external-dns on the cluster
