### ISSUE TITLE
Add nodeSelector to deployments activeMQ, filestore, repository and search

### ISSUE THREAD

**Issue by shazada** [Alfresco/acs-deployment#566]
Similar to the PostgreSQL template or the common (Digital Workspace) template add the following to each deployment
```
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

**Comment by shazada** [comment]
Any news on this? Should I make a PR?

**Comment by mteodori** [comment]
Thanks @shazada this is definitely something interesting but we should cover also custom labels and introduce a common template for all services in order to avoid excessive duplication
