### ISSUE TITLE
Official docker compose files for Alfresco Enterprise versions?

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/acs-deployment#571]
Hi,

is this the official repo for the docker compose files for Alfresco Enterprise 7 and later?
I have seen the docker-compose files for 6.2 and a file docker-compose.yml which is updated regularly also with milestone versions. 

What is your strategy regarding versioning of the docker compose files? 
How to make sure as partner/customer to use supported versions of all components?
For example, how can I get access to the latest supported enterprise version 7.0? I have downloaded the docker-compose file from your official alfresco website because I was not sure how to get the correct version here in GitHub.

Thanks

**Comment by alxgomz** [comment]
Hi @jgoldhammer ,

If you want to work "older" version then the versioned (6.x) docker-compose files are good to use on master.
If you want to use the latest avaialble alfresco GA release then you shoud l use the "default" docker-compose.yml from the appropriate release tag (no -Mx or -RCy tag).
I believe this should help bringing some clarity: https://github.com/Alfresco/acs-deployment#versioning
As  the default docker-compose.yml always bring the latest and greatest, once 7.1 is out a new 7.0 versioned file should be made available here for ppl to use it

**Comment by jgoldhammer** [comment]
Thanks for clarification. I will close the issue as this answers my question!
