### ISSUE TITLE
postgresql-syncservice is at the wrong level in the values.yaml file

### ISSUE THREAD

**Issue by srbonham** [Alfresco/acs-deployment#579]
While trying to turn off postgresql-syncservice (setting to false), i noticed this did not have any effect on the deployment.  After some digging, the yaml structure is incorrect.  It should be like:

```
alfresco-sync-service:
  postgresql-syncservice:
    enabled: false
```

instead its referenced like
```

postgresql-syncservice
  enabled:false
  ...
```

Just wanted to let everyone know.

**Comment by mteodori** [comment]
Can you please go back to the issue rather than your solution and show your command line that failed with expected result? thanks

**Comment by srbonham** [comment]
The issue is that the postgresql-syncservice values from the 7.0.N values file has no effect on the helm chart.  The fix is to appropriately reference the postgresql-syncservice as such:

`...
alfresco-sync-service:
  postgresql-syncservice:
    enabled: false
  ...
`

instead of 

`postgresql-syncservice
  enabled:false
  ...`


thats as specific as I can be.

**Comment by mteodori** [comment]
I don't think that is the problem as if you call `helm template --set global.tracking.sharedsecret=secret --set postgresql-syncservice.nameOverride=myname helm/alfresco-content-service` the value is applied

**Comment by gionn** [comment]
Tracking internally as OPSEXP-1930

> alfresco-sync-service subchart doesn’t currently [depends](https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/charts/alfresco-sync-service/Chart.yaml#L13) on the postgresql bitnami chart and it relies on the [main chart handling the postgresql dependency](https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/Chart.yaml#L31) configuration.
> 
> That implies that the alfresco-sync-service subchart can’t have any visibility on how the embedded postgres database has been configured. For that reason the alfresco-sync-service subchart is using a duplicated postgresql-syncservice object in the templates it manages, which is really not the same instance which the main chart use to configure the actual database, leading to duplication and eventual inconsistencies (right now it works just because the very same values are copied in both structures)
