### ISSUE TITLE
Application Load Balancer support for acs-ingress ingress-nginx/ingress-nginx

### ISSUE THREAD

**Issue by hhettiarachchi** [Alfresco/acs-deployment#608]
The deployment of the acs-ingress ingress-nginx/ingress-nginx  version=3.7.1 creates a classic load balancer on AWS which is deprecated. Is there a newer version for this that creates an Application Load Balancer?

**Comment by mteodori** [comment]
Question for https://github.com/kubernetes/ingress-nginx but anyway you can always use controller.service.type=NodePort and attach to an ALB created outside helm, for example via terraform before you call helm
