### ISSUE TITLE
Initial password not working

### ISSUE THREAD

**Issue by johanmorenolds** [Alfresco/acs-deployment#61]
I have not been able to login to a new deployment, i tried the defaults alfresco//alfresco, admin//admin but none has worked

**Comment by timijntema** [comment]
admin//admin is working for me

**Comment by killerboot** [comment]
Hi, admin/admin is the default password.
Please make sure that Alfresco container started and running.

**Comment by johanmorenolds** [comment]
hi pals, thanks for the quick reply, i tried the admin/admin but it didn't work. but checking in "Kitematic" i see that one container with the name Angry_turing didn't start, there are no logs, could this be the problem? the docker compose i used created 11 containers, from this 11, only this one with the name angry-turing didn't start. any suggestions? is there any log that i could send to you in order to may be find the problem?

**Comment by killerboot** [comment]
@johanmorenolds 
Can you please describe how do you deploy ACS?
How much RAM do you have on your environment?

**Comment by johanmorenolds** [comment]
ohhh Killerbot!, you are so clever, your question gave me the answers, i had shared just 2gb of RAM, i moved it to 4GB, and (Listo!) worked as charm.

Thank you very much
