### ISSUE TITLE
Digital Workspace not working from Docker-compose

### ISSUE THREAD

**Issue by rstoops-wiley** [Alfresco/acs-deployment#615]
Down load the compose file and went to start it just to see how it would work for sdk5 development.
The docker-compose doesn't fire up Activiti and through the configuration, it doesn't look like a way to stop it from trying.

main-es2015.ea3017e1197127c62081.js:1 ERROR Error: Uncaught (in promise): Object: {"error":{"original":null,"response":{"req":{"method":"POST","url":"$%7BAPP_CONFIG_ECM_HOST%7D/alfresco/api/-default-/public/authentication/versions/1/tickets","data":{"userId":"admin","password":"admin"},"headers":{"authorization":"Basic YWRtaW46YWRtaW4=","content-type":"application/json","accept":"application/json"}},"xhr":{"__zone_symbol__readystatechangefalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:readystatechange","zone":"angular","runCount":6}],"__zone_symbol__progressfalse":[{"type":"eventTask","state":"scheduled","source":"XMLHttpRequest.addEventListener:progress","zone":"angular","runCount":0}],"__zone_symbol__xhrSync":false,"__zone_symbol__xhrURL":"$%7BAPP_CONFIG_ECM_HOST%7D/alfresco/api/-default-/public/authentication/versions/1/tickets","__zone_symbol__xhrScheduled":true,"__zone_symbol__xhrErrorBeforeScheduled":false,"__zone_symbol__xhrTask":{"type":"macroTask","state":"scheduled","source":"XMLHttpRequest.send","zone":"angular","runCount":0}},"text":"","statusText":"","statusCode":404,"status":404,"statusType":4,"info":false,"ok":false,"redirect":false,"clientError":true,"serverError":false,"error":{"status":404,"method":"POST","url":"$%7BAPP_CONFIG_ECM_HOST%7D/alfresco/api/-default-/public/authentication/versions/1/tickets"},"created":false,"accepted":false,"noContent":false,"badRequest":false,"unauthorized":false,"notAcceptable":false,"forbidden":false,"notFound":true,"unprocessableEntity":false,"headers":{"connection":"keep-alive","content-length":"0","date":"Thu, 14 Oct 2021 20:51:05 GMT","server":"nginx/1.18.0","content-type":null},"header":{"connection":"keep-alive","content-length":"0","date":"Thu, 14 Oct 2021 20:51:05 GMT","server":"nginx/1.18.0","content-type":null},"type":"","links":{},"body":null},"status":404}}
    at b (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at b (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at polyfills-es2015.b9ee7abdc92c815a3f85.js:1
    at l.invokeTask (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at Object.onInvokeTask (main-es2015.ea3017e1197127c62081.js:1)
    at l.invokeTask (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at i.runTask (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at m (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at u.invokeTask [as invoke] (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
    at h (polyfills-es2015.b9ee7abdc92c815a3f85.js:1)
Yi @ main-es2015.ea3017e1197127c62081.js:1
handleError @ main-es2015.ea3017e1197127c62081.js:1
next @ main-es2015.ea3017e1197127c62081.js:1
n @ main-es2015.ea3017e1197127c62081.js:1
__tryOrUnsub @ main-es2015.ea3017e1197127c62081.js:1
next @ main-es2015.ea3017e1197127c62081.js:1
_next @ main-es2015.ea3017e1197127c62081.js:1
next @ main-es2015.ea3017e1197127c62081.js:1
next @ main-es2015.ea3017e1197127c62081.js:1
emit @ main-es2015.ea3017e1197127c62081.js:1
(anonymous) @ main-es2015.ea3017e1197127c62081.js:1
invoke @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
run @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
runOutsideAngular @ main-es2015.ea3017e1197127c62081.js:1
onHandleError @ main-es2015.ea3017e1197127c62081.js:1
handleError @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
runGuarded @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
n.microtaskDrainDone @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
m @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
invokeTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
h @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
p @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
XMLHttpRequest.send (async)
_ @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
scheduleTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
onScheduleTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
scheduleTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
scheduleTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
scheduleMacroTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
p @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
(anonymous) @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
C.r.<computed> @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
_._end @ main-es2015.ea3017e1197127c62081.js:1
_.end @ main-es2015.ea3017e1197127c62081.js:1
(anonymous) @ main-es2015.ea3017e1197127c62081.js:1
D @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
callHostApi @ main-es2015.ea3017e1197127c62081.js:1
callApi @ main-es2015.ea3017e1197127c62081.js:1
createTicket @ main-es2015.ea3017e1197127c62081.js:1
(anonymous) @ main-es2015.ea3017e1197127c62081.js:1
D @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
login @ main-es2015.ea3017e1197127c62081.js:1
_loginBPMECM @ main-es2015.ea3017e1197127c62081.js:1
login @ main-es2015.ea3017e1197127c62081.js:1
login @ main-es2015.ea3017e1197127c62081.js:1
performLogin @ main-es2015.ea3017e1197127c62081.js:1
onSubmit @ main-es2015.ea3017e1197127c62081.js:1
(anonymous) @ main-es2015.ea3017e1197127c62081.js:1
Eo @ main-es2015.ea3017e1197127c62081.js:1
s @ main-es2015.ea3017e1197127c62081.js:1
(anonymous) @ main-es2015.ea3017e1197127c62081.js:1
invokeTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
onInvokeTask @ main-es2015.ea3017e1197127c62081.js:1
invokeTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
runTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
invokeTask @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
h @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
p @ polyfills-es2015.b9ee7abdc92c815a3f85.js:1
Show 27 more frames
polyfills-es2015.b9ee7abdc92c815a3f85.js:1 GET http://localhost:8080/$%7BAPP_CONFIG_BPM_HOST%7D/activiti-app/app/authentication/ 404

**Comment by alxgomz** [comment]
hmmm... I think there was at some point a problem with the docker image. Can you please make sure the adw image you're using has this digest: `1e8c2034c933`
If not please pull again

**Comment by mteodori** [comment]
stale
