### ISSUE TITLE
Where can I download alfresco-elasticsearch-connector-distribution Docker Compose? 

### ISSUE THREAD

**Issue by chanwitkepha** [Alfresco/acs-deployment#616]
Please help because According to Search Enterprise 3.0 Installation Guide URL below. I tried to search in Both Hyland community and GitHub also but I cannot find https://github.com/Alfresco/alfresco-elasticsearch-connector Repo or URL to download, Thank you.

https://docs.alfresco.com/search-enterprise/latest/install/

**Comment by mteodori** [comment]
helm chart supports solr not es
