### ISSUE TITLE
Make alfresco-search inclusion configurable

### ISSUE THREAD

**Issue by anghelutar** [Alfresco/acs-deployment#634]
Currently parameter alfresco-search.enabled has no effect, the subchart is always included, it is not possible to use a custom deployment for the search subsystem:
https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/README.md

Solution: add a condition in https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/Chart.yaml 

- name: alfresco-search
  condition: alfresco-search.enabled

**Comment by mteodori** [comment]
This will be fixed once we implement the option to use the new search based on ElasticSearch

**Comment by mteodori** [comment]
thanks @anghelutar this is now tracked as OPSEXP-1388
