### ISSUE TITLE
Add possibility to mount Alfresco license

### ISSUE THREAD

**Issue by ariksidney** [Alfresco/acs-deployment#635]
Hi there,

We had some issues applying a new ACS license this year, so this is more like a feature request.

Currently, when building images with the Alfresco SDK 4.x, the license is added to the image under _tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/license/_. This has the huge drawback that if a new license is required, a new image must be built and deployed (which can be quite tricky regarding to frozen zones common in large-ish companies).

For the Helm charts, a much cleaner solution in my eyes would be to add the license to a Kubernetes secret and then mount this secret to the ACS pods under _tomcat/shared/classes/alfresco/extension/license_. This would have the huge advantage that license changes would be image-independant and could be done by simply update the secret and restarting the acs deployment.

For Docker Compose, the license file could just be mounted to the same folder with a bound volume mount.

If this would be a viable solution, I could create a PR for the Helm charts and Docker Compose deployment.

Additionally, a change to the SDK would make sense aswell, so that by default the license is mounted and not built into the image. Based on my observations, if licenses on both paths are found, it will pick the one at _tomcat/webapps/alfresco/WEB-INF/classes/alfresco/extension/license/_.

**Comment by mteodori** [comment]
Thanks @ariksidney this suggestion is very useful, a PR would definitely be very welcome

**Comment by ariksidney** [comment]
Hi @mteodori looks like this is possible now with ACS 7.2? https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/examples/alf_license.md

**Comment by mteodori** [comment]
Yea, it hasn't been released yet but happy for you to try it out from master
