### ISSUE TITLE
Deploying Alfresco Enterprise Fails to deploy sub charts

### ISSUE THREAD

**Issue by darnone** [Alfresco/acs-deployment#636]
We are deploying Alfresco Enterprise with Helm into EKS following the AWS services install instructions and have noticed that alfresco-search and alfresco-sync-service are not deployed. (In addition, digital-workspace is missing as a subchart)  We used ```helm template``` to generate the manifests and resources for those components and they appear in the generated manifests **but are not deployed**. Is there some other setting required to deploy these? Also where is digital-workspace coming from?  I see it in the generated manifest but it is not deployed either.  You answer is deeply appreciated.

**Comment by alxgomz** [comment]
Hi @darnone we never use `helm template` but instead `helm install` as per the docutmentation in this project.
Also it is not clear what is not working for you. Are you missing the whole deployment of commponent? Is the deployment present but the pods just never coming up? What error are you facing specifically?...
I'm personnally not sure how to help without a wider understanding iof the issue.
Also when deploying, make sure you do provide a secret name as `global. alfrescoRegistryPullSecrets` with valid credentials to the quay.io registry as some images are not publicly available (like digital-workspace).
See:  [https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/eks-deployment.md#docker-registry-secret](https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/eks-deployment.md#docker-registry-secret)

**Comment by alxgomz** [comment]
OK thank you @darnone for clarifications:
1. containerized ACS will gather configuration mostly from JAVA_OPTS env variable. It's passed to containers using a configMap called `RELEASE_NAME-repository-configmap`. You can tweak the JAVA_OPTS to your needs using the `.Values.repository.environment`
2. It really should and actually it is deployed on the test envs I have checked. Do you not see the deployment at all or is the deployment failing? If the later then what is the error you get?
3. digital-workspace is also a dependency and depends on `.Values.alfresco-digital-workspace.enabled,alfresco-digital-workspace.enabled`. You should just needs to change this value to disable it.

**Comment by darnone** [comment]
@alxgomz,

Thanks for your reply
1. OK I see the configmap.  Is there a documented list of Java opts somewhere? Is this where I would configure AD or is that done in the UI?
2. I don't see alfresco-sync-service at all more do I see any errors.  The deployments I have are attached.  What is odd is helm generated the manifest - service, deployment, ingress, config, and a secret.
3. OK that is good to know.

**Comment by mteodori** [comment]
there's a list of properties here https://github.com/Alfresco/acs-deployment/blob/master/docs/properties-reference.md
but I would rather go to the alfresco docs site for an explanation in contextt:  https://docs.alfresco.com/content-services/latest/

sync-service is enabled by default
https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/values.yaml#L792-L794
