### ISSUE TITLE
ACS Deployment fails on Kubernetes version 1.22

### ISSUE THREAD

**Issue by RadaKichenin** [Alfresco/acs-deployment#638]
Hi,
Deployment on Kubernetes v1.22 fails because networking.k8s.io/v1beta1 is depricated. New version only supports networking.k8s.io/v1.
Is this update in pipeline ? 

Regards

**Comment by mteodori** [comment]
Thanks for reporting, this is not planned yet.

At the moment we test with AWS EKS that has 1.21 as current default so the API is deprecated but not removed yet https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

Feel free to submit a PR to support later versions of k8s
