### ISSUE TITLE
Avoid injecting passwords as environment variables

### ISSUE THREAD

**Issue by mossroy** [Alfresco/acs-deployment#640]
Most passwords are currently injected via environment variables, for both docker-compose and helm.

It seems unsafe to me. See for example https://blog.nillsf.com/index.php/2020/02/24/dont-use-environment-variables-in-kubernetes-to-consume-secrets/

At least when using Kubernetes/Helm, it's possible to inject secrets in files. Most open-source docker images support this : it's the case with postgres for example (see https://github.com/docker-library/docs/blob/master/postgres/README.md#docker-secrets)

Would it be possible, like for postgres, to pass for example a `db.password.file` environment variable, pointing to a file containing the password? (Kubernetes can natively inject the corresponding Secret in it)
Or to pass the password through alfresco-global.properties instead of environment variables?

**Comment by mteodori** [comment]
it's a standard practice and no less secure then passing them via files, we'll probably move sensitive properties to kubernetes secrets instead
