### ISSUE TITLE
could I still using postgres 13.1?

### ISSUE THREAD

**Issue by antoniorv75** [Alfresco/acs-deployment#643]
My environment are setup in 7.1 with docker-compose but I am using postgres 13.1 instead the container supplied for postgres. I could see you change your database to 13.3, I was wondering if I can still using the 13.1 instead 13.3, would be the 13.1 compatible with alfresco 7.2?

Thank you in advance

**Comment by mteodori** [comment]
Platform support for containerised deployment follows the official documentation pages which suggests:
* PostgreSQL 13.3 for ACS 7.1 latest GA https://docs.alfresco.com/content-services/latest/support/
* PostgreSQL 13.1 for ACS 7.0 https://docs.alfresco.com/content-services/7.0/support/

Hope this helps
