### ISSUE TITLE
ACS Deploy fails with `unauthorized: access to the requested resource is not authorized`

### ISSUE THREAD

**Issue by ixtogt** [Alfresco/acs-deployment#660]
Hi everyone, hen do I deploy Alfresco with this command

# docker-compose -f community-docker-compose.yml up

it gives me this error

Pulling solr6 (quay.io/alfresco/search-services:2.1.0-SNAPSHOT)...
ERROR: unauthorized: access to the requested resource is not authorized

so i find the history of the community-docker-compose.yml history here and see this change:

from this    image: alfresco/alfresco-search-services:2.0.2
to this         image: quay.io/alfresco/search-services:2.1.0-SNAPSHOT

there will be some problem if i revert that line to the previous one? because if i do that everything works without any problem.

regards,

**Comment by gionn** [comment]
Hello, thanks for reporting.

We are in the process of releasing a new alfresco-search version (a matter of days) that requires some changes that have been tested and accidentally merged in https://github.com/Alfresco/acs-deployment/pull/655, sorry for that.

We are going to fix this during the release process.

**Comment by kelsen** [comment]
A lot of headaches because of this line:
```
solr6:
    image: quay.io/alfresco/search-services:2.1.0-SNAPSHOT
```
change it to:
```
solr6:
    image: alfresco/alfresco-search-services:2.1.0-A10
```

**Comment by raupach** [comment]
I am not sure whether this works or not. I have several errors in the log:

2022-03-12 21:07:27.002 ERROR (qtp1816089958-14) [   x:alfresco] o.a.s.h.RequestHandlerBase java.lang.UnsupportedOperationException

**Comment by alxgomz** [comment]
As explained in the [README.md](https://github.com/Alfresco/acs-deployment#versioning):
> The master branch of this repository now contains the artifacts required to deploy both the the latest work-in-progress development version and previous stable versions of ACS.

So it's indeed possible an image might have some issue. If you want to have a setup that's working and supported, be sure to use a tag release from the [release/tags page](https://github.com/Alfresco/acs-deployment/tags)

backscene: there are some changes coming to the next release around search so that's likely to be the source of the problems you're facing
