### ISSUE TITLE
unauthorized: access to the requested resource is not authorized

### ISSUE THREAD

**Issue by raupach** [Alfresco/acs-deployment#663]
Just tested:
docker-compose -f community-docker-compose.yml up

Error:
Pulling solr6 (quay.io/alfresco/search-services:)...
ERROR: unauthorized: access to the requested resource is not authorized

**Comment by gionn** [comment]
Hello,

this is already been reported, see https://github.com/Alfresco/acs-deployment/issues/660#issuecomment-1056964651

Thanks.
