### ISSUE TITLE
Comunity docker-copose - wrong image for solr?

### ISSUE THREAD

**Issue by szykulat** [Alfresco/acs-deployment#688]
Hi 

community-docker-compose.yml has Solr image set to  quay.io/alfresco/search-services:2.1.0-SNAPSHOT which I think is repository for enterprise version, I could not get it so I change it to alfresco/alfresco-search-services:2.0.3, want to confirm that it should work with this version too?

**Comment by mteodori** [comment]
confirmed, will be fixed with release see https://github.com/Alfresco/acs-deployment/commit/dda1e3ae4275ee2dc2dcbb62752965546672b1fc

**Comment by mteodori** [comment]
fixed in #687
