### ISSUE TITLE
[Enterprise Search 3.x] Please update helm for it

### ISSUE THREAD

**Issue by scila1996** [Alfresco/acs-deployment#691]
I want to use ACS with Enterprise Search using Elasticsearch follow here

https://docs.alfresco.com/search-enterprise/latest/install/#install-using-helm

But helm does not have parameter  or value/document for it. Please update ... !

**Comment by mteodori** [comment]
Thanks @scila1996 for reporting, it's currently in the works and tracked internally as OPSEXP-1369.
I wasn't aware of the documentation not in sync, will try and reach the owners to clarify

**Comment by scila1996** [comment]
> Thanks @scila1996 for reporting, it's currently in the works and tracked internally as [OPSEXP-1369](https://alfresco.atlassian.net/browse/OPSEXP-1369). I wasn't aware of the documentation not in sync, will try and reach the owners to clarify

Hi @mteodori, we were pay for license of Enterprise Search 3.1, and need to install soon, please update helm chart for it :((

**Comment by mteodori** [comment]
fixed in #693
