### ISSUE TITLE
quay.io/alfresco/search-services image

### ISSUE THREAD

**Issue by vprince1** [Alfresco/acs-deployment#730]
I was trying to install Alfresco Helm chart 5.2.0. I found that the search services image could not be downloaded due to access issue. After debugging, I found that the alfresco-search helm chart was using an image (quay.io/alfresco/search-services:2.0.3) that is not accessible. The alfresco-search [values.yaml](https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/charts/alfresco-search/values.yaml) references this image. The correct image that should be used is "alfresco/alfresco-search-services" (used in docker-compose). I think that we should either make quay.io/alfresco/search-services  available or the searchServicesImage.repository should be set to "alfresco/alfresco-search-services". For now, I am able to pass in the correct image during the helm install.

Thanks,
Vijay

**Comment by mteodori** [comment]
for community install you should use community values as explained in the README which references the image on docker hub https://github.com/Alfresco/acs-deployment/blob/v5.2.0/helm/alfresco-content-services/community_values.yaml#L32-L34

**Comment by vprince1** [comment]
Can you let me know what image I should use for enterprise install? If it is quay.io/alfresco/search-services:2.0.3, then our quay.io account does not have access to it. We can access other enterprise images like quay.io/alfresco/alfresco-content-repository. But, quay.io/alfresco/search-services:2.0.3 is not accessible.

Thanks,
Vijay

**Comment by alxgomz** [comment]
Hi @vprince1 
the image the helm charts points to is the right one for enterprise deployment. Your account may indeed lack the necessary permission but we can't help on that matter. I would advice you contact enterprise support through the [support portal](https://support.alfresco.com).

Regards,

**Comment by vprince1** [comment]
Thanks for the details. I was able to reach out to Alfresco support to get me access to this image. Can you kindly let me know if there is any difference between quay.io/alfresco/search-services:2.0.3 and alfresco/alfresco-search-services:2.0.3 image? Since the [docker-compose](https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/docker-compose.yml#L119) file uses the non-quay.io image for enterprise, I want to make sure we are using the correct images in both cases.

Thanks

**Comment by alxgomz** [comment]
yes they are the same indeed (Core Search2 being one of the few components that's identical in both community and enterprise) but note that related images will only be available in quay.io (zepellin, insight engine and Search3 for instance). So I would stick to the enterprise registry once entitlement is fixed.
