### ISSUE TITLE
Liveness probe failed: Get "http://10.1.0.230:8090/live": dial tcp 10.1.0.230:8090: connect: connection refused

### ISSUE THREAD

**Issue by lihc520** [Alfresco/acs-deployment#742]
I made an error in the docker Desktop Deployment community

**Comment by lihc520** [comment]
>  
10.1.0.230 is acs-alfresco-cs-imagemagick

**Comment by lihc520** [comment]
The same is true of other components

**Comment by gionn** [comment]
Hello,

can you check logs of that pod for errors and paste them here?

Thanks.

**Comment by lihc520** [comment]
> 

<img width="1802" alt="image" src="https://user-images.githubusercontent.com/69955018/181180647-d4d313a0-6b2d-489a-9dcd-f89a29abcc56.png">
I just can't see any other errors

**Comment by lihc520** [comment]
> 

org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.

I see this information, but I don't know if it's relevant

**Comment by lihc520** [comment]
> Hello,
> 
> can you check logs of that pod for errors and paste them here?
> 
> Thanks.

2022-07-27 07:13:00,026  ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-2] 06270002 Failed to connect or to read the response from T-Engine on http://localhost:8090//transform/config?configVersion=2
2022-07-27 07:13:00,051  ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-1] 06270003 Failed to connect or to read the response from T-Engine on http://localhost:8090//transform/config?configVersion=2

**Comment by lihc520** [comment]
> > Hello,
> > can you check logs of that pod for errors and paste them here?
> > Thanks.
> 
> 2022-07-27 07:13:00,026 ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-2] 06270002 Failed to connect or to read the response from T-Engine on http://localhost:8090//transform/config?configVersion=2 2022-07-27 07:13:00,051 ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-1] 06270003 Failed to connect or to read the response from T-Engine on http://localhost:8090//transform/config?configVersion=2

now this is acs-alfresco-cs-repository pod error log

**Comment by lihc520** [comment]
> > > Hello,
> > > can you check logs of that pod for errors and paste them here?
> > > Thanks.
> > 
> > 
> > 2022-07-27 07:13:00,026 ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-2] 06270002 Failed to connect or to read the response from T-Engine on http://localhost:8090//transform/config?configVersion=2 2022-07-27 07:13:00,051 ERROR [content.transform.LocalTransformServiceRegistry] [QuartzScheduler_Worker-1] 06270003 Failed to connect or to read the response from T-Engine on http://localhost:8090//transform/config?configVersion=2
> 
> now this is acs-alfresco-cs-repository pod error log

<img width="2555" alt="image" src="https://user-images.githubusercontent.com/69955018/181185393-968eb81b-2133-4f94-98c0-a4cc88d35d34.png">

**Comment by alxgomz** [comment]
Hi @lihc520 ,

We believe this has been fixed by https://github.com/Alfresco/acs-deployment/pull/805

Hence I'm closing this issue
