### ISSUE TITLE
Question: how "api/solr" access is protected?

### ISSUE THREAD

**Issue by angelborroy-ks** [Alfresco/acs-deployment#79]
I'm trying to find where SOLR Tracker invocations to Alfresco Repository are protected as now both services are using plain HTTP. 

Any additional rules should be applied to include this protection in a real prod scenario?

**Comment by angelborroy-ks** [comment]
Ok, I'm closing this.

It's fixed at https://github.com/Alfresco/acs-deployment/commit/129db29e3e8d8fbb0417d75516fd3c669a30e2a1

Thanks!

**Comment by derekhulley** [comment]
Thanks.
