### ISSUE TITLE
Outbound SMTP subsystem not configured if email.server.enabled not set to true

### ISSUE THREAD

**Issue by AFaust** [Alfresco/acs-deployment#800]
In the current Helm chart state, it is impossible to configure the outbound SMTP capability unless one also enables the inbound SMTP server, as in the config-repository file the outbound config properties are included in the conditional block guarded by `email.server.enabled` (beginning in line 91, see https://github.com/Alfresco/acs-deployment/blob/master/helm/alfresco-content-services/templates/config-repository.yaml#L91)

**Comment by gionn** [comment]
as per [docs(https://docs.alfresco.com/content-services/latest/config/email/), indeed it seems that two distinct features are treated as they were only one.

Thanks for reporting!

Internally tracked with OPSEXP-1826
