### ISSUE TITLE
Minimum memory settings too large

### ISSUE THREAD

**Issue by dgrumieaux** [Alfresco/acs-deployment#89]
Hi,

While attempting to run this on my local development machine, I tuned down the memory settings dramatically to fit within my system limitations (I can at most dedicate 6 GB and 3 cores). The "alfresco" container is crashing due to a lack of enough dedicated resources. Are there plans to reduce the memory requirements of the deployment? It makes local development hard.
Thanks

**Comment by derekhulley** [comment]
You will need more, out of the box, even If you tried to use _docker-compose_.
We have to strike a balance between people trying to do real stuff with the trial and machine resources.

Take the _docker-compose.yml_ file and tweak the memory settings to suit your environment.  6GB is not a limit we will be targeting for the file as it stands.
