### ISSUE TITLE
When database.external=true, the repository deployment is missing volumes

### ISSUE THREAD

**Issue by kikinsama** [Alfresco/acs-deployment#894]
I tried deploying with Helm using an external database and got an error. Trying to inspect the generated yaml files (doing a dry-run) showed that the {name}-alfresco-cs-repository deployment was generated without any volume definition:

![image](https://user-images.githubusercontent.com/29970002/220449232-a01feef7-05c4-4f00-8638-969971cfd1d4.png)

The problem seems to be in helm/alfresco-content-services/templates/deployment-repository.yaml, line 124. I've noticed that {{- if eq .Values.database.external false }} is closed at the end of the file, instead of being closed before the "volumes:" definition

**Comment by gionn** [comment]
Looks like a bug indeed and it was broken since we started to have more initcontainers and volumes in addition to the database ones.

We should push that conditional inside and only around resources that are related to database.

Internally tracking as OPSEXP-2002
