### ISSUE TITLE
installation helm : error shared secret for solr

### ISSUE THREAD

**Issue by hafsaSaih** [Alfresco/acs-deployment#900]
Hello !
I am trying to deploy acs-deployment in minikube for a simple school project. I have tried the steps in this tutorial (option 2)  .
[https://github.com/AlfrescoArchive/acs-community-deployment/blob/master/docs/helm-deployment-minikube.md](url)
 Everything seems to work fine .
at the last step I got an error : Installation failed : you need to provide a shared secret for solr/repo authentification. 
I got stuck to this error.
Ps: I didn't configure anything that has to do with solr or sahred secret at my server and I don't have a clear idea if I have to do so

**Comment by hafsaSaih** [comment]
![error](https://user-images.githubusercontent.com/126255352/222790839-771535e0-ce8b-4b2f-bfb1-f214df18c0c1.jpeg)

**Comment by alxgomz** [comment]
The documentation you linked do not apply to this repo. It's an old project, hence the AlfrescoArchive name.
You should instead use this one https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md  that's  what is most likely to apply to minikube (we have abandonned minikube for rancher-desktop/docker-desktop, so I can't guarantee it'll work).

Keep in mind the helm deployment has some rather heavy requirements.

Finally the solr secret configuration will be handled automatically by the helm chart. You simply need to tell it which sharedsecret to use (we don't generate secrets for you). It's also in the doc.

**Comment by hafsaSaih** [comment]
thank you.
I really appreciate it
