### ISSUE TITLE
Can't deploy ACS with helm chart on kubernetes 1.25 cluster

### ISSUE THREAD

**Issue by volkotyk** [Alfresco/acs-deployment#901]
Main chart has an embedded sub-chart **alfresco-sync-service** which one has **hpa-syncservice.yaml** template with hardcoded API version value
`apiVersion: autoscaling/v2beta1`
This API version [no longer supports](https://kubernetes.io/docs/reference/using-api/deprecation-guide/) in kubernetes 1.25
Error log:
> Error: Failed to render chart: exit status 1: coalesce.go:223: warning: destination for postgresql-syncservice.persistence.storageClass is a table. Ignoring non-table value ()
>   Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "alfresco-content-services-alfresco-sync-service-hpa" namespace: "" from "": no matches for kind "HorizontalPodAutoscaler" in version "autoscaling/v2beta1"

Part of hpa-syncservice.yam

> {{- if .Values.syncservice.enabled }}
> {{- if .Values.syncservice.horizontalPodAutoscaling.enabled }}
> apiVersion: autoscaling/v2beta1
> kind: HorizontalPodAutoscaler
>   metadata:

**Comment by alxgomz** [comment]
We kicked HPA from master but it's still unreleased. We're not yet sure that will be enough to support 1.25 for godd but stay tuned.

**Comment by volkotyk** [comment]
I see it in tags at this repo, but it looks like a major change in the helm chart.
Is it possible to do a fast fix of API version in HPA template and release a minor update like 5.3.1?

**Comment by alxgomz** [comment]
Not really. Back porting support for newer kubernetes version is not something we do. We try to maintain the chart compatible with older version of alfresco so newer charts can always deploy older (but still supported) version so the latest charts is usable in most cases.
Also we  would have to setup proper test against 1.25 to ensure compat, which we don't have for now.
If you really can't upgrade the chart I think your best bet is to just cherry pick f41ef77 on the 5.3.0 tag (which I think should apply smoothly)

P.S: I realize that's not ideal for automated deloyments

**Comment by gionn** [comment]
Hello, charts should be now compatibile with 1.25 (are current internal pipeline is running on EKS 1.25)
