### ISSUE TITLE
User search failed in Share

### ISSUE THREAD

**Issue by MaelVB** [Alfresco/acs-deployment#915]
Hi, I just ran `docker-compose -f community-docker-compose.yml up -d`

No clear errors in the server logs

But when I go to the Users page in the Share admin, I can't get any user
![image](https://user-images.githubusercontent.com/33149290/231998730-a3cc7976-d406-4cfa-ab36-54e3cb656e27.png)

In the client console I get this error:
![image](https://user-images.githubusercontent.com/33149290/231999675-de5a9327-0f8c-492c-b0fa-3896af6ef5f3.png)

**Comment by gionn** [comment]
Unfortunately this is related to an upstream bug https://github.com/Alfresco/acs-community-packaging/issues/367 and there is little we can do here our docker compose.
