### ISSUE TITLE
5.4.0-SNAPSHOT is failing installing due to search dependency helper

### ISSUE THREAD

**Issue by shazada** [Alfresco/acs-deployment#923]
I was testing the latest chart for some local issues with the 5.4.0-M2 tag, but the latest -SNAPSHOT isn't building anymore.

`Error: template: alfresco-content-services/templates/deployment-repository.yaml:24:28: executing "alfresco-content-services/templates/deployment-repository.yaml" at <include (print $.Template.BasePath "/config-repository.yaml") .>: error calling include: template: alfresco-content-services/templates/config-repository.yaml:35:10: executing "alfresco-content-services/templates/config-repository.yaml" at <include "repository.indexConfig" .>: error calling include: template: alfresco-content-services/templates/_helpers-search.tpl:24:44: executing "repository.indexConfig" at <index $.Subcharts "alfresco-search" "Chart">: error calling index: index of untyped nil`

I do the following:

`helm upgrade --install acs -f values.yaml -f 7.2.N_values.yaml -f local_values.yaml . `

local_values.yaml is the following:
```

global:
  alfrescoRegistryPullSecrets: regcred
  tracking:
    auth: secret
    sharedsecret: secret
```

**Comment by gionn** [comment]
which are the contents of that `_helpers-search.tpl`?

it's not part of the templates of this chart at that version, see [here](https://github.com/Alfresco/acs-deployment/tree/v5.4.0-SNAPSHOT/helm/alfresco-content-services/templates).

**Comment by shazada** [comment]
Maybe it was an old chart in the charts folder, let me see if I can clean it.

**Comment by shazada** [comment]
I'll close this, can't reproduce this.
