### ISSUE TITLE
Repostiory extraVolumeMounts is never used in the REPO deployment

### ISSUE THREAD

**Issue by shazada** [Alfresco/acs-deployment#930]
So the extraVolumeMounts is never used in the REPO Deployment

- Documentation points to that it exist:
https://github.com/Alfresco/acs-deployment/blob/v5.4.0-M3/helm/alfresco-content-services/README.md?plain=1#L262
- Also the **values.yaml** also refers to this variable which doesn't exist
https://github.com/Alfresco/acs-deployment/blob/v5.4.0-M3/helm/alfresco-content-services/values.yaml#L112

It's only used in the share-deployments which doesn't really makes a lot of sense, but doesn't hurt either.
https://github.com/Alfresco/acs-deployment/blob/v5.4.0-M3/helm/alfresco-content-services/templates/deployment-share.yaml#L50

**Comment by gionn** [comment]
I remember noticing it during the migration to the new alfresco-helm-charts repo, hopefully I will fix it there.

Thanks for reporting 🙏🏻

**Comment by alexander-heuser-tc** [comment]
When will this issue be resolved?
