### ISSUE TITLE
Problem connecting to oracle 19c database

### ISSUE THREAD

**Issue by ITMPGIT** [Alfresco/acs-deployment#952]
hello I'm trying to use the oracle 19c database, with the stack in docker I made a new build of the image "alfresco/alfresco-content-repository-community:7.4.0.1" to add the jdbc to make the connection, but I get the following errors :

My Dockerfile:
```sh
FROM alfresco/alfresco-content-repository-community:7.4.0.1
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CATALINA_HOME/lib
USER root
RUN yum install wget -y && cd $CATALINA_HOME/lib && wget https://download.oracle.com/otn-pub/otn_software/jdbc/1919/ojdbc8.jar
```
Logs container:
 nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Cannot create PoolableConnectionFactory (ORA-28040: No matching authentication protocol)
2023-06-21T16:54:04,688 [] ERROR [web.context.ContextLoader] [main] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.beans.factory.config.CustomEditorConfigurer#0' defined in class path resource [alfresco/core-services-context.xml]: Cannot resolve reference to bean 'customPropertyEditorRegistrar' while setting bean property 'propertyEditorRegistrars' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customPropertyEditorRegistrar' defined in class path resource [alfresco/core-services-context.xml]: Cannot resolve reference to bean 'NamespaceService' while setting bean property 'namespaceService';

**Comment by alxgomz** [comment]
I'm no oracle expert but the error tends to show the driver is properly.
Anyway, Alfresco community do not work with Oracle DB. This is an Alfresco enterprise only feature.
