### ISSUE TITLE
Unable to deploy over docker compose.

### ISSUE THREAD

**Issue by fadsm** [Alfresco/acs-deployment#96]
Hi Guys,

I cannot deploy using docker compose due to an error on YAML file:

$docker-compose up
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
   in "./docker-compose.yml", line:385, column 26

May you please fix the sintax?

**Comment by derekhulley** [comment]
Please raise an issue at issues.alfresco.com, providing all the usual detail about the OS, versions of docker, etc.

**Comment by derekhulley** [comment]
Also, you might want to use the https://github.com/Alfresco/acs-community-deployment and submit a pull request, referencing that in the issue you raise.

**Comment by derekhulley** [comment]
Closing as Community version should be used.
