### ISSUE TITLE
Creating renditions for previous versions broke the restore operation

### ISSUE THREAD

**Issue by airesearch2** [Alfresco/acs-deployment#988]
Steps to reproduce:
In alfresco share:
1) Upload image 1. 
2) Upload new version (image 2) in alfresco share.

In rest api(http://ip:8080/api-explorer/
3) Create rendition for **not latest version**
curl:
`curl -X POST "http://ip:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/5dd77fae-e30f-4009-a45d-0b91a4788bbd/versions/1.0/renditions" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"id\": \"imgpreview\"}"`
url: `http://dt0007.ce.local:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/5dd77fae-e30f-4009-a45d-0b91a4788bbd/versions/1.0/renditions`

In alfresco share or in rest api:
4) Try to restore version 1. 
4.1) In ui(alfresco share):
Message "Cannot restore image 1";
Status 500
log in console
`"07180471 Wrapped Exception (with status template): 071853490 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/repository/version/revert.post.json.js': nodeRef is a mandatory parameter"
`
4.2) In rest api: 
Status 400.
url: 
`http://ip:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/5dd77fae-e30f-4009-a45d-0b91a4788bbd/versions/1.0/revert`
log:
```
{
  "error": {
    "errorKey": "framework.exception.ApiDefault",
    "statusCode": 400,
    "briefSummary": "nodeRef is a mandatory parameter",
    "stackTrace": "For security reasons the stack trace is no longer displayed, but the property is kept for previous versions"
    "descriptionURL": "https://api-explorer.alfresco.com"
  }
}
```
I would appreciate it if someone could fix this problem or suggest a way around this bug.

**Comment by gionn** [comment]
Hello, can you confirm if you are using docker compose or helm charts and which image versions of alfresco/share/transform?

**Comment by airesearch2** [comment]
Hello. We use docker compose   .

alfresco/alfresco-content-repository-community:7.0.0
alfresco/alfresco-share:7.0.0
transform-core-aio:alfresco/alfresco-transform-core-aio:2.3.10

I also install the latest version locally via docker compose. Here the
problem also reproduces.
https://docs.alfresco.com/content-services/community/install/containers/docker-compose/
image: docker.io/alfresco-content-repository-community:7.4.0.1
image: docker.io/alfresco/alfresco-share:7.4.0.1
image: alfresco/alfresco-transform-core-aio:4.0.0


пт, 18 авг. 2023 г. в 13:18, Giovanni Toraldo ***@***.***>:
